"""V1 Audio endpoint - OpenAI-compatible audio API for transcriptions, translations, and speech."""

import logging
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from pydantic import BaseModel, Field
from sqlmodel import Session, select

from app.api.deps import get_db
from app.core.config import settings
from app.models import AudioJob, Model
from app.models import File as FileModel

logger = logging.getLogger(__name__)

router = APIRouter()


class TranscriptionResponse(BaseModel):
    """Transcription response."""

    text: str


class VerboseTranscriptionResponse(BaseModel):
    """Verbose transcription response."""

    task: str = "transcribe"
    language: str
    duration: float
    text: str
    segments: list[dict[str, str]] | None = None


class TranslationResponse(BaseModel):
    """Translation response."""

    text: str


class VerboseTranslationResponse(BaseModel):
    """Verbose translation response."""

    task: str = "translate"
    language: str = "en"
    duration: float
    text: str
    segments: list[dict[str, str]] | None = None


class SpeechRequest(BaseModel):
    """Speech generation request."""

    model: str
    input: str
    voice: str = "alloy"
    response_format: Literal["mp3", "wav", "flac", "opus", "aac"] = "mp3"
    speed: float = Field(default=1.0, ge=0.25, le=4.0)


def _validate_audio_file(file: UploadFile) -> None:
    """Validate audio file format."""
    allowed_extensions = [".wav", ".mp3", ".flac", ".ogg", ".m4a", ".webm"]
    file_extension = Path(file.filename or "").suffix.lower()
    if file_extension not in allowed_extensions:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid audio format: {file_extension}. Allowed: {', '.join(allowed_extensions)}",
        )


@router.post("/audio/transcriptions", response_model=TranscriptionResponse)
async def create_transcription(
    file: UploadFile = File(...),
    model: str = Form(...),
    language: str | None = Form(None),
    prompt: str | None = Form(None),
    response_format: Literal["json", "text", "srt", "verbose_json"] = Form("json"),
    temperature: float = Form(0.0),
    db: Session = Depends(get_db),
) -> TranscriptionResponse | VerboseTranscriptionResponse:
    """
    Transcribe audio to text.

    Args:
        file: Audio file to transcribe
        model: Whisper model ID
        language: Optional language code
        prompt: Optional transcription hint
        response_format: Response format (json, text, srt, verbose_json)
        temperature: Sampling temperature
    """
    _validate_audio_file(file)

    statement = select(Model).where(Model.name == model)
    model_instance = db.exec(statement).first()

    if not model_instance:
        raise HTTPException(status_code=404, detail=f"Model '{model}' not found")

    try:
        audio_dir = Path(
            settings.AUDIO_PATH
            if hasattr(settings, "AUDIO_PATH")
            else "/tmp/inference-matrix/audio"
        )
        audio_dir.mkdir(parents=True, exist_ok=True)

        file_id = f"file-{uuid.uuid4().hex[:12]}"
        file_extension = Path(file.filename or "").suffix
        file_path = audio_dir / f"{file_id}{file_extension}"

        content = await file.read()
        with open(file_path, "wb") as f:
            f.write(content)

        file_uuid = uuid.uuid4()
        file_model = FileModel(
            id=file_uuid,
            filename=file.filename or "audio.wav",
            path=str(file_path.absolute()),
            size_bytes=len(content),
            mime_type=file.content_type or "audio/wav",
            checksum_sha256="",
            purpose="transcription",
            status="uploaded",
        )

        db.add(file_model)
        db.commit()
        db.refresh(file_model)

        audio_job = AudioJob(
            id=uuid.uuid4(),
            job_type="transcription",
            input_file_id=file_model.id,
            model_id=model_instance.id,
            parameters={
                "language": language,
                "prompt": prompt,
                "temperature": temperature,
                "response_format": response_format,
            },
            status="processing",
        )

        db.add(audio_job)
        db.commit()

        text = "Transcription would be generated by whisper.cpp here."

        audio_job.status = "completed"
        audio_job.result_text = text
        audio_job.completed_at = datetime.now(UTC)
        db.add(audio_job)
        db.commit()

        if response_format == "verbose_json":
            return VerboseTranscriptionResponse(
                task="transcribe",
                language=language or "en",
                duration=0.0,
                text=text,
                segments=[],
            )
        else:
            return TranscriptionResponse(text=text)

    except Exception as e:
        logger.error(f"Transcription error: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to transcribe audio: {e}")


@router.post("/audio/translations", response_model=TranslationResponse)
async def create_translation(
    file: UploadFile = File(...),
    model: str = Form(...),
    prompt: str | None = Form(None),
    response_format: Literal["json", "text", "srt", "verbose_json"] = Form("json"),
    temperature: float = Form(0.0),
    db: Session = Depends(get_db),
) -> TranslationResponse | VerboseTranslationResponse:
    """
    Translate audio to English text.

    Args:
        file: Audio file to translate
        model: Whisper model ID
        prompt: Optional translation hint
        response_format: Response format (json, text, srt, verbose_json)
        temperature: Sampling temperature
    """
    _validate_audio_file(file)

    statement = select(Model).where(Model.name == model)
    model_instance = db.exec(statement).first()

    if not model_instance:
        raise HTTPException(status_code=404, detail=f"Model '{model}' not found")

    try:
        audio_dir = Path(
            settings.AUDIO_PATH
            if hasattr(settings, "AUDIO_PATH")
            else "/tmp/inference-matrix/audio"
        )
        audio_dir.mkdir(parents=True, exist_ok=True)

        file_id = f"file-{uuid.uuid4().hex[:12]}"
        file_extension = Path(file.filename or "").suffix
        file_path = audio_dir / f"{file_id}{file_extension}"

        content = await file.read()
        with open(file_path, "wb") as f:
            f.write(content)

        file_uuid = uuid.uuid4()
        file_model = FileModel(
            id=file_uuid,
            filename=file.filename or "audio.wav",
            path=str(file_path.absolute()),
            size_bytes=len(content),
            mime_type=file.content_type or "audio/wav",
            checksum_sha256="",
            purpose="translation",
            status="uploaded",
        )

        db.add(file_model)
        db.commit()
        db.refresh(file_model)

        audio_job = AudioJob(
            id=uuid.uuid4(),
            job_type="translation",
            input_file_id=file_model.id,
            model_id=model_instance.id,
            parameters={
                "prompt": prompt,
                "temperature": temperature,
                "response_format": response_format,
            },
            status="processing",
        )

        db.add(audio_job)
        db.commit()

        text = "Translation would be generated by whisper.cpp here."

        audio_job.status = "completed"
        audio_job.result_text = text
        audio_job.completed_at = datetime.now(UTC)
        db.add(audio_job)
        db.commit()

        if response_format == "verbose_json":
            return VerboseTranslationResponse(
                task="translate",
                language="en",
                duration=0.0,
                text=text,
                segments=[],
            )
        else:
            return TranslationResponse(text=text)

    except Exception as e:
        logger.error(f"Translation error: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to translate audio: {e}")


@router.post("/audio/speech")
async def create_speech(
    request: SpeechRequest,
    db: Session = Depends(get_db),
):
    """
    Generate speech from text (TTS).

    Args:
        request: Speech generation request
    """
    statement = select(Model).where(Model.name == request.model)
    model_instance = db.exec(statement).first()

    if not model_instance:
        raise HTTPException(
            status_code=404, detail=f"Model '{request.model}' not found"
        )

    try:
        audio_dir = Path(
            settings.AUDIO_PATH
            if hasattr(settings, "AUDIO_PATH")
            else "/tmp/inference-matrix/audio"
        )
        audio_dir.mkdir(parents=True, exist_ok=True)

        output_filename = f"speech-{uuid.uuid4().hex[:12]}.{request.response_format}"
        output_path = audio_dir / output_filename

        with open(output_path, "wb") as f:
            f.write(b"")

        from fastapi.responses import FileResponse

        return FileResponse(
            path=str(output_path),
            filename=output_filename,
            media_type=f"audio/{request.response_format}",
            headers={
                "X-Speech-Model": request.model,
                "X-Speech-Voice": request.voice,
            },
        )

    except Exception as e:
        logger.error(f"Speech generation error: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to generate speech: {e}")
