// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { adminAdminHealthData, adminAdminHealthResponses, adminClearCacheData, adminClearCacheErrors, adminClearCacheResponses, adminCreateDefinitionData, adminCreateDefinitionErrors, adminCreateDefinitionResponses, adminCreateMachineData, adminCreateMachineErrors, adminCreateMachineResponses, adminDeleteDefinitionData, adminDeleteDefinitionErrors, adminDeleteDefinitionResponses, adminDeleteMachineData, adminDeleteMachineErrors, adminDeleteMachineResponses, adminGetDefinitionData, adminGetDefinitionErrors, adminGetDefinitionResponses, adminGetInstanceData, adminGetInstanceErrors, adminGetInstanceResponses, adminGetMachineData, adminGetMachineErrors, adminGetMachineResponses, adminListDefinitionsData, adminListDefinitionsResponses, adminListInstancesData, adminListInstancesResponses, adminListMachinesData, adminListMachinesResponses, adminListResponsesData, adminListResponsesErrors, adminListResponsesResponses, adminOverviewStatsData, adminOverviewStatsResponses, adminPatchDefinitionData, adminPatchDefinitionErrors, adminPatchDefinitionResponses, adminPatchMachineData, adminPatchMachineErrors, adminPatchMachineResponses, adminPruneStorageData, adminPruneStorageErrors, adminPruneStorageResponses, adminRegisterProviderData, adminRegisterProviderErrors, adminRegisterProviderResponses, adminUsageStatsData, adminUsageStatsErrors, adminUsageStatsResponses, chatCreateChatCompletionData, chatCreateChatCompletionResponses, modelsListModelsData, modelsListModelsResponses, responsesCreateResponseData, responsesCreateResponseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AdminService {
    /**
     * Admin Health
     *
     * Liveness and version probe for the admin service.
     */
    public static adminHealth<ThrowOnError extends boolean = true>(options?: Options<adminAdminHealthData, ThrowOnError>) {
        return (options?.client ?? client).get<adminAdminHealthResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/health',
            ...options
        });
    }
    
    /**
     * Register Provider
     *
     * Register (or re-register) a provider instance against its definition.
     */
    public static registerProvider<ThrowOnError extends boolean = true>(options: Options<adminRegisterProviderData, ThrowOnError>) {
        return (options.client ?? client).post<adminRegisterProviderResponses, adminRegisterProviderErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/providers/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Machines
     */
    public static listMachines<ThrowOnError extends boolean = true>(options?: Options<adminListMachinesData, ThrowOnError>) {
        return (options?.client ?? client).get<adminListMachinesResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/machines',
            ...options
        });
    }
    
    /**
     * Create Machine
     */
    public static createMachine<ThrowOnError extends boolean = true>(options: Options<adminCreateMachineData, ThrowOnError>) {
        return (options.client ?? client).post<adminCreateMachineResponses, adminCreateMachineErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/machines',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Machine
     */
    public static deleteMachine<ThrowOnError extends boolean = true>(options: Options<adminDeleteMachineData, ThrowOnError>) {
        return (options.client ?? client).delete<adminDeleteMachineResponses, adminDeleteMachineErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/machines/{machine_id}',
            ...options
        });
    }
    
    /**
     * Get Machine
     */
    public static getMachine<ThrowOnError extends boolean = true>(options: Options<adminGetMachineData, ThrowOnError>) {
        return (options.client ?? client).get<adminGetMachineResponses, adminGetMachineErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/machines/{machine_id}',
            ...options
        });
    }
    
    /**
     * Patch Machine
     */
    public static patchMachine<ThrowOnError extends boolean = true>(options: Options<adminPatchMachineData, ThrowOnError>) {
        return (options.client ?? client).patch<adminPatchMachineResponses, adminPatchMachineErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/machines/{machine_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Definitions
     */
    public static listDefinitions<ThrowOnError extends boolean = true>(options?: Options<adminListDefinitionsData, ThrowOnError>) {
        return (options?.client ?? client).get<adminListDefinitionsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/definitions',
            ...options
        });
    }
    
    /**
     * Create Definition
     */
    public static createDefinition<ThrowOnError extends boolean = true>(options: Options<adminCreateDefinitionData, ThrowOnError>) {
        return (options.client ?? client).post<adminCreateDefinitionResponses, adminCreateDefinitionErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/definitions',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Definition
     */
    public static deleteDefinition<ThrowOnError extends boolean = true>(options: Options<adminDeleteDefinitionData, ThrowOnError>) {
        return (options.client ?? client).delete<adminDeleteDefinitionResponses, adminDeleteDefinitionErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/definitions/{definition_id}',
            ...options
        });
    }
    
    /**
     * Get Definition
     */
    public static getDefinition<ThrowOnError extends boolean = true>(options: Options<adminGetDefinitionData, ThrowOnError>) {
        return (options.client ?? client).get<adminGetDefinitionResponses, adminGetDefinitionErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/definitions/{definition_id}',
            ...options
        });
    }
    
    /**
     * Patch Definition
     */
    public static patchDefinition<ThrowOnError extends boolean = true>(options: Options<adminPatchDefinitionData, ThrowOnError>) {
        return (options.client ?? client).patch<adminPatchDefinitionResponses, adminPatchDefinitionErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/definitions/{definition_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Instances
     */
    public static listInstances<ThrowOnError extends boolean = true>(options?: Options<adminListInstancesData, ThrowOnError>) {
        return (options?.client ?? client).get<adminListInstancesResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/instances',
            ...options
        });
    }
    
    /**
     * Get Instance
     */
    public static getInstance<ThrowOnError extends boolean = true>(options: Options<adminGetInstanceData, ThrowOnError>) {
        return (options.client ?? client).get<adminGetInstanceResponses, adminGetInstanceErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/instances/{instance_id}',
            ...options
        });
    }
    
    /**
     * Clear Cache
     */
    public static clearCache<ThrowOnError extends boolean = true>(options: Options<adminClearCacheData, ThrowOnError>) {
        return (options.client ?? client).post<adminClearCacheResponses, adminClearCacheErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/instances/{instance_id}/cache/clear',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Prune Storage
     */
    public static pruneStorage<ThrowOnError extends boolean = true>(options: Options<adminPruneStorageData, ThrowOnError>) {
        return (options.client ?? client).post<adminPruneStorageResponses, adminPruneStorageErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/instances/{instance_id}/storage/prune',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Responses
     */
    public static listResponses<ThrowOnError extends boolean = true>(options?: Options<adminListResponsesData, ThrowOnError>) {
        return (options?.client ?? client).get<adminListResponsesResponses, adminListResponsesErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/responses',
            ...options
        });
    }
    
    /**
     * Usage Stats
     */
    public static usageStats<ThrowOnError extends boolean = true>(options?: Options<adminUsageStatsData, ThrowOnError>) {
        return (options?.client ?? client).get<adminUsageStatsResponses, adminUsageStatsErrors, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/stats/usage',
            ...options
        });
    }
    
    /**
     * Overview Stats
     */
    public static overviewStats<ThrowOnError extends boolean = true>(options?: Options<adminOverviewStatsData, ThrowOnError>) {
        return (options?.client ?? client).get<adminOverviewStatsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/admin/api/stats/overview',
            ...options
        });
    }
}

export class ResponsesService {
    /**
     * Create Response
     */
    public static createResponse<ThrowOnError extends boolean = true>(options?: Options<responsesCreateResponseData, ThrowOnError>) {
        return (options?.client ?? client).post<responsesCreateResponseResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/v1/responses',
            ...options
        });
    }
}

export class ChatService {
    /**
     * Create Chat Completion
     */
    public static createChatCompletion<ThrowOnError extends boolean = true>(options?: Options<chatCreateChatCompletionData, ThrowOnError>) {
        return (options?.client ?? client).post<chatCreateChatCompletionResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/v1/chat/completions',
            ...options
        });
    }
}

export class ModelsService {
    /**
     * List Models
     */
    public static listModels<ThrowOnError extends boolean = true>(options?: Options<modelsListModelsData, ThrowOnError>) {
        return (options?.client ?? client).get<modelsListModelsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/v1/models',
            ...options
        });
    }
}
