// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ActionBody
 */
export type ActionBody = {
    /**
     * Dry Run
     */
    dry_run?: boolean;
    /**
     * Force
     */
    force?: boolean;
};

/**
 * BackendActionBody
 *
 * `wait_for_running`: hold the ack until the backend reports running.
 *
 * Default false (202-style): the provider starts the boot in the
 * background and the caller polls the instance. True mirrors the
 * scheduler's contract and is bounded by
 * ``settings.BACKEND_BOOT_TIMEOUT_SECONDS`` — long enough for a cold
 * engine-side download, but it does keep the request open that whole time.
 */
export type BackendActionBody = {
    /**
     * Wait For Running
     */
    wait_for_running?: boolean;
};

/**
 * DefinitionCreate
 */
export type DefinitionCreate = {
    /**
     * Alias
     */
    alias: string;
    /**
     * Provider Type
     */
    provider_type?: string | null;
    /**
     * Backend Config
     */
    backend_config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Vram Required Bytes
     */
    vram_required_bytes?: number;
    /**
     * Idle Timeout Seconds
     */
    idle_timeout_seconds?: number;
    /**
     * Capacity
     */
    capacity?: number;
    /**
     * Registration Token
     */
    registration_token?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * DefinitionPatch
 */
export type DefinitionPatch = {
    /**
     * Alias
     */
    alias?: string | null;
    /**
     * Provider Type
     */
    provider_type?: string | null;
    /**
     * Backend Config
     */
    backend_config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Vram Required Bytes
     */
    vram_required_bytes?: number | null;
    /**
     * Idle Timeout Seconds
     */
    idle_timeout_seconds?: number | null;
    /**
     * Capacity
     */
    capacity?: number | null;
    /**
     * Registration Token
     */
    registration_token?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MachineCreate
 */
export type MachineCreate = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Host
     */
    host?: string | null;
    /**
     * Dns
     */
    dns?: string | null;
    /**
     * Ip
     */
    ip?: string | null;
    /**
     * Total Vram Bytes
     */
    total_vram_bytes?: number;
};

/**
 * MachinePatch
 */
export type MachinePatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Host
     */
    host?: string | null;
    /**
     * Dns
     */
    dns?: string | null;
    /**
     * Ip
     */
    ip?: string | null;
    /**
     * Total Vram Bytes
     */
    total_vram_bytes?: number | null;
};

/**
 * RegistrationRequest
 *
 * Body sent by provider_lib.admin_client.AdminClient.register().
 *
 * ``schema`` (Phase 12) is the provider package's committed
 * ``schema.json`` (JSON Schema 2020-12 for this type's
 * ``backend_config``). The admin derives the fingerprint itself; the
 * provider never sends it separately.
 *
 * TRANSITION (Phase 12): ``schema`` is optional until every provider
 * package ships a real ``schema.json`` (Phase D) — an admin-first
 * deploy must not 422 the currently-deployed providers that don't send
 * it yet. See the schema-omitted path in ``register_provider``.
 */
export type RegistrationRequest = {
    /**
     * Machine Uid
     */
    machine_uid: string;
    /**
     * Registration Token
     */
    registration_token: string;
    /**
     * Provider Type
     */
    provider_type: string;
    /**
     * Schema
     */
    schema?: {
        [key: string]: unknown;
    } | null;
    /**
     * Version
     */
    version: string;
    /**
     * Port
     */
    port?: number;
    /**
     * Hardware
     */
    hardware?: {
        [key: string]: unknown;
    };
    /**
     * Metrics Categories
     */
    metrics_categories?: Array<string>;
    /**
     * Registered At
     */
    registered_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type adminAdminHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/health';
};

export type adminAdminHealthResponses = {
    /**
     * Response Admin-Admin Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type adminAdminHealthResponse = adminAdminHealthResponses[keyof adminAdminHealthResponses];

export type adminRegisterProviderData = {
    body: RegistrationRequest;
    path?: never;
    query?: never;
    url: '/admin/api/providers/register';
};

export type adminRegisterProviderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminRegisterProviderError = adminRegisterProviderErrors[keyof adminRegisterProviderErrors];

export type adminRegisterProviderResponses = {
    /**
     * Response Admin-Register Provider
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminRegisterProviderResponse = adminRegisterProviderResponses[keyof adminRegisterProviderResponses];

export type adminListMachinesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/machines';
};

export type adminListMachinesResponses = {
    /**
     * Response Admin-List Machines
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminListMachinesResponse = adminListMachinesResponses[keyof adminListMachinesResponses];

export type adminCreateMachineData = {
    body: MachineCreate;
    path?: never;
    query?: never;
    url: '/admin/api/machines';
};

export type adminCreateMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateMachineError = adminCreateMachineErrors[keyof adminCreateMachineErrors];

export type adminCreateMachineResponses = {
    /**
     * Response Admin-Create Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminCreateMachineResponse = adminCreateMachineResponses[keyof adminCreateMachineResponses];

export type adminDeleteMachineData = {
    body?: never;
    path: {
        /**
         * Machine Id
         */
        machine_id: string;
    };
    query?: never;
    url: '/admin/api/machines/{machine_id}';
};

export type adminDeleteMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminDeleteMachineError = adminDeleteMachineErrors[keyof adminDeleteMachineErrors];

export type adminDeleteMachineResponses = {
    /**
     * Response Admin-Delete Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminDeleteMachineResponse = adminDeleteMachineResponses[keyof adminDeleteMachineResponses];

export type adminGetMachineData = {
    body?: never;
    path: {
        /**
         * Machine Id
         */
        machine_id: string;
    };
    query?: never;
    url: '/admin/api/machines/{machine_id}';
};

export type adminGetMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetMachineError = adminGetMachineErrors[keyof adminGetMachineErrors];

export type adminGetMachineResponses = {
    /**
     * Response Admin-Get Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetMachineResponse = adminGetMachineResponses[keyof adminGetMachineResponses];

export type adminPatchMachineData = {
    body: MachinePatch;
    path: {
        /**
         * Machine Id
         */
        machine_id: string;
    };
    query?: never;
    url: '/admin/api/machines/{machine_id}';
};

export type adminPatchMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminPatchMachineError = adminPatchMachineErrors[keyof adminPatchMachineErrors];

export type adminPatchMachineResponses = {
    /**
     * Response Admin-Patch Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminPatchMachineResponse = adminPatchMachineResponses[keyof adminPatchMachineResponses];

export type adminListDefinitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/definitions';
};

export type adminListDefinitionsResponses = {
    /**
     * Response Admin-List Definitions
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminListDefinitionsResponse = adminListDefinitionsResponses[keyof adminListDefinitionsResponses];

export type adminCreateDefinitionData = {
    body: DefinitionCreate;
    path?: never;
    query?: never;
    url: '/admin/api/definitions';
};

export type adminCreateDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateDefinitionError = adminCreateDefinitionErrors[keyof adminCreateDefinitionErrors];

export type adminCreateDefinitionResponses = {
    /**
     * Response Admin-Create Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminCreateDefinitionResponse = adminCreateDefinitionResponses[keyof adminCreateDefinitionResponses];

export type adminDeleteDefinitionData = {
    body?: never;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/admin/api/definitions/{definition_id}';
};

export type adminDeleteDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminDeleteDefinitionError = adminDeleteDefinitionErrors[keyof adminDeleteDefinitionErrors];

export type adminDeleteDefinitionResponses = {
    /**
     * Response Admin-Delete Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminDeleteDefinitionResponse = adminDeleteDefinitionResponses[keyof adminDeleteDefinitionResponses];

export type adminGetDefinitionData = {
    body?: never;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/admin/api/definitions/{definition_id}';
};

export type adminGetDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetDefinitionError = adminGetDefinitionErrors[keyof adminGetDefinitionErrors];

export type adminGetDefinitionResponses = {
    /**
     * Response Admin-Get Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetDefinitionResponse = adminGetDefinitionResponses[keyof adminGetDefinitionResponses];

export type adminPatchDefinitionData = {
    body: DefinitionPatch;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/admin/api/definitions/{definition_id}';
};

export type adminPatchDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminPatchDefinitionError = adminPatchDefinitionErrors[keyof adminPatchDefinitionErrors];

export type adminPatchDefinitionResponses = {
    /**
     * Response Admin-Patch Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminPatchDefinitionResponse = adminPatchDefinitionResponses[keyof adminPatchDefinitionResponses];

export type adminListInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/instances';
};

export type adminListInstancesResponses = {
    /**
     * Response Admin-List Instances
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminListInstancesResponse = adminListInstancesResponses[keyof adminListInstancesResponses];

export type adminGetInstanceData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}';
};

export type adminGetInstanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetInstanceError = adminGetInstanceErrors[keyof adminGetInstanceErrors];

export type adminGetInstanceResponses = {
    /**
     * Response Admin-Get Instance
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetInstanceResponse = adminGetInstanceResponses[keyof adminGetInstanceResponses];

export type adminClearCacheData = {
    /**
     * Body
     */
    body?: ActionBody | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/cache/clear';
};

export type adminClearCacheErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminClearCacheError = adminClearCacheErrors[keyof adminClearCacheErrors];

export type adminClearCacheResponses = {
    /**
     * Response Admin-Clear Cache
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminClearCacheResponse = adminClearCacheResponses[keyof adminClearCacheResponses];

export type adminPruneStorageData = {
    /**
     * Body
     */
    body?: ActionBody | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/storage/prune';
};

export type adminPruneStorageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminPruneStorageError = adminPruneStorageErrors[keyof adminPruneStorageErrors];

export type adminPruneStorageResponses = {
    /**
     * Response Admin-Prune Storage
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminPruneStorageResponse = adminPruneStorageResponses[keyof adminPruneStorageResponses];

export type adminStartBackendData = {
    /**
     * Body
     */
    body?: BackendActionBody | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/backend/start';
};

export type adminStartBackendErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminStartBackendError = adminStartBackendErrors[keyof adminStartBackendErrors];

export type adminStartBackendResponses = {
    /**
     * Response Admin-Start Backend
     *
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type adminStartBackendResponse = adminStartBackendResponses[keyof adminStartBackendResponses];

export type adminStopBackendData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/backend/stop';
};

export type adminStopBackendErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminStopBackendError = adminStopBackendErrors[keyof adminStopBackendErrors];

export type adminStopBackendResponses = {
    /**
     * Response Admin-Stop Backend
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminStopBackendResponse = adminStopBackendResponses[keyof adminStopBackendResponses];

export type adminRestartBackendData = {
    /**
     * Body
     */
    body?: BackendActionBody | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/backend/restart';
};

export type adminRestartBackendErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminRestartBackendError = adminRestartBackendErrors[keyof adminRestartBackendErrors];

export type adminRestartBackendResponses = {
    /**
     * Response Admin-Restart Backend
     *
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type adminRestartBackendResponse = adminRestartBackendResponses[keyof adminRestartBackendResponses];

export type adminInitializeInstanceData = {
    /**
     * Body
     */
    body?: BackendActionBody | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/initialize';
};

export type adminInitializeInstanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminInitializeInstanceError = adminInitializeInstanceErrors[keyof adminInitializeInstanceErrors];

export type adminInitializeInstanceResponses = {
    /**
     * Response Admin-Initialize Instance
     *
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type adminInitializeInstanceResponse = adminInitializeInstanceResponses[keyof adminInitializeInstanceResponses];

export type adminGetInstanceLogsData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: {
        /**
         * Kind
         */
        kind?: string;
        /**
         * Since
         */
        since?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/api/instances/{instance_id}/logs';
};

export type adminGetInstanceLogsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetInstanceLogsError = adminGetInstanceLogsErrors[keyof adminGetInstanceLogsErrors];

export type adminGetInstanceLogsResponses = {
    /**
     * Response Admin-Get Instance Logs
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetInstanceLogsResponse = adminGetInstanceLogsResponses[keyof adminGetInstanceLogsResponses];

export type adminListProviderTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/provider-types';
};

export type adminListProviderTypesResponses = {
    /**
     * Response Admin-List Provider Types
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminListProviderTypesResponse = adminListProviderTypesResponses[keyof adminListProviderTypesResponses];

export type adminGetProviderTypeData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/admin/api/provider-types/{name}';
};

export type adminGetProviderTypeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetProviderTypeError = adminGetProviderTypeErrors[keyof adminGetProviderTypeErrors];

export type adminGetProviderTypeResponses = {
    /**
     * Response Admin-Get Provider Type
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetProviderTypeResponse = adminGetProviderTypeResponses[keyof adminGetProviderTypeResponses];

export type adminCommitPendingData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/admin/api/provider-types/{name}/pending/commit';
};

export type adminCommitPendingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCommitPendingError = adminCommitPendingErrors[keyof adminCommitPendingErrors];

export type adminCommitPendingResponses = {
    /**
     * Response Admin-Commit Pending
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminCommitPendingResponse = adminCommitPendingResponses[keyof adminCommitPendingResponses];

export type adminDismissPendingData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/admin/api/provider-types/{name}/pending/dismiss';
};

export type adminDismissPendingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminDismissPendingError = adminDismissPendingErrors[keyof adminDismissPendingErrors];

export type adminDismissPendingResponses = {
    /**
     * Response Admin-Dismiss Pending
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminDismissPendingResponse = adminDismissPendingResponses[keyof adminDismissPendingResponses];

export type adminSearchModelsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search
         *
         * Search query
         */
        search: string;
        /**
         * Limit
         *
         * Max results
         */
        limit?: number;
        /**
         * Full
         *
         * Include full model info
         */
        full?: boolean;
        /**
         * Filter
         *
         * File-type filter: 'gguf' applies the legacy HF 'config=gguf' repo filter; 'all' is a general model search (halogen .hgn repos are not GGUF-configured and must stay discoverable).
         */
        filter?: 'all' | 'gguf';
    };
    url: '/admin/api/huggingface/search';
};

export type adminSearchModelsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminSearchModelsError = adminSearchModelsErrors[keyof adminSearchModelsErrors];

export type adminSearchModelsResponses = {
    /**
     * Response Admin-Search Models
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminSearchModelsResponse = adminSearchModelsResponses[keyof adminSearchModelsResponses];

export type adminListRepoFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repo Id
         *
         * HuggingFace repository ID (e.g. 'unsloth/Qwen3-27B-GGUF')
         */
        repo_id: string;
        /**
         * Include All
         *
         * Include unclassified/irrelevant files (default: recognized kinds only)
         */
        include_all?: boolean;
    };
    url: '/admin/api/huggingface/files';
};

export type adminListRepoFilesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminListRepoFilesError = adminListRepoFilesErrors[keyof adminListRepoFilesErrors];

export type adminListRepoFilesResponses = {
    /**
     * Response Admin-List Repo Files
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminListRepoFilesResponse = adminListRepoFilesResponses[keyof adminListRepoFilesResponses];

export type adminListResponsesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/admin/api/responses';
};

export type adminListResponsesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminListResponsesError = adminListResponsesErrors[keyof adminListResponsesErrors];

export type adminListResponsesResponses = {
    /**
     * Response Admin-List Responses
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminListResponsesResponse = adminListResponsesResponses[keyof adminListResponsesResponses];

export type adminUsageStatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/api/stats/usage';
};

export type adminUsageStatsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUsageStatsError = adminUsageStatsErrors[keyof adminUsageStatsErrors];

export type adminUsageStatsResponses = {
    /**
     * Response Admin-Usage Stats
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminUsageStatsResponse = adminUsageStatsResponses[keyof adminUsageStatsResponses];

export type adminOverviewStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/stats/overview';
};

export type adminOverviewStatsResponses = {
    /**
     * Response Admin-Overview Stats
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminOverviewStatsResponse = adminOverviewStatsResponses[keyof adminOverviewStatsResponses];

export type responsesCreateResponseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/responses';
};

export type responsesCreateResponseResponses = {
    /**
     * Response Responses-Create Response
     *
     * Successful Response
     */
    200: unknown;
};

export type chatCreateChatCompletionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/chat/completions';
};

export type chatCreateChatCompletionResponses = {
    /**
     * Response Chat-Create Chat Completion
     *
     * Successful Response
     */
    200: unknown;
};

export type modelsListModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type modelsListModelsResponses = {
    /**
     * Response Models-List Models
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type modelsListModelsResponse = modelsListModelsResponses[keyof modelsListModelsResponses];
