// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ActionBody
 */
export type ActionBody = {
    /**
     * Dry Run
     */
    dry_run?: boolean;
    /**
     * Force
     */
    force?: boolean;
};

/**
 * DefinitionCreate
 */
export type DefinitionCreate = {
    /**
     * Alias
     */
    alias: string;
    /**
     * Provider Type
     */
    provider_type: string;
    /**
     * Backend Config
     */
    backend_config?: {
        [key: string]: unknown;
    };
    /**
     * Vram Required Bytes
     */
    vram_required_bytes?: number;
    /**
     * Idle Timeout Seconds
     */
    idle_timeout_seconds?: number;
    /**
     * Capacity
     */
    capacity?: number;
    /**
     * Registration Token
     */
    registration_token?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * DefinitionPatch
 */
export type DefinitionPatch = {
    /**
     * Alias
     */
    alias?: string | null;
    /**
     * Provider Type
     */
    provider_type?: string | null;
    /**
     * Backend Config
     */
    backend_config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Vram Required Bytes
     */
    vram_required_bytes?: number | null;
    /**
     * Idle Timeout Seconds
     */
    idle_timeout_seconds?: number | null;
    /**
     * Capacity
     */
    capacity?: number | null;
    /**
     * Registration Token
     */
    registration_token?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MachineCreate
 */
export type MachineCreate = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Host
     */
    host?: string | null;
    /**
     * Dns
     */
    dns?: string | null;
    /**
     * Ip
     */
    ip?: string | null;
    /**
     * Total Vram Bytes
     */
    total_vram_bytes?: number;
};

/**
 * MachinePatch
 */
export type MachinePatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Host
     */
    host?: string | null;
    /**
     * Dns
     */
    dns?: string | null;
    /**
     * Ip
     */
    ip?: string | null;
    /**
     * Total Vram Bytes
     */
    total_vram_bytes?: number | null;
};

/**
 * RegistrationRequest
 *
 * Body sent by provider_lib.admin_client.AdminClient.register().
 */
export type RegistrationRequest = {
    /**
     * Machine Uid
     */
    machine_uid: string;
    /**
     * Registration Token
     */
    registration_token: string;
    /**
     * Provider Type
     */
    provider_type: string;
    /**
     * Version
     */
    version: string;
    /**
     * Port
     */
    port?: number;
    /**
     * Hardware
     */
    hardware?: {
        [key: string]: unknown;
    };
    /**
     * Metrics Categories
     */
    metrics_categories?: Array<string>;
    /**
     * Registered At
     */
    registered_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type adminAdminHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/health';
};

export type adminAdminHealthResponses = {
    /**
     * Response Admin-Admin Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type adminAdminHealthResponse = adminAdminHealthResponses[keyof adminAdminHealthResponses];

export type adminRegisterProviderData = {
    body: RegistrationRequest;
    path?: never;
    query?: never;
    url: '/admin/api/providers/register';
};

export type adminRegisterProviderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminRegisterProviderError = adminRegisterProviderErrors[keyof adminRegisterProviderErrors];

export type adminRegisterProviderResponses = {
    /**
     * Response Admin-Register Provider
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminRegisterProviderResponse = adminRegisterProviderResponses[keyof adminRegisterProviderResponses];

export type adminListMachinesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/machines';
};

export type adminListMachinesResponses = {
    /**
     * Response Admin-List Machines
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminListMachinesResponse = adminListMachinesResponses[keyof adminListMachinesResponses];

export type adminCreateMachineData = {
    body: MachineCreate;
    path?: never;
    query?: never;
    url: '/admin/api/machines';
};

export type adminCreateMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateMachineError = adminCreateMachineErrors[keyof adminCreateMachineErrors];

export type adminCreateMachineResponses = {
    /**
     * Response Admin-Create Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminCreateMachineResponse = adminCreateMachineResponses[keyof adminCreateMachineResponses];

export type adminDeleteMachineData = {
    body?: never;
    path: {
        /**
         * Machine Id
         */
        machine_id: string;
    };
    query?: never;
    url: '/admin/api/machines/{machine_id}';
};

export type adminDeleteMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminDeleteMachineError = adminDeleteMachineErrors[keyof adminDeleteMachineErrors];

export type adminDeleteMachineResponses = {
    /**
     * Response Admin-Delete Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminDeleteMachineResponse = adminDeleteMachineResponses[keyof adminDeleteMachineResponses];

export type adminGetMachineData = {
    body?: never;
    path: {
        /**
         * Machine Id
         */
        machine_id: string;
    };
    query?: never;
    url: '/admin/api/machines/{machine_id}';
};

export type adminGetMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetMachineError = adminGetMachineErrors[keyof adminGetMachineErrors];

export type adminGetMachineResponses = {
    /**
     * Response Admin-Get Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetMachineResponse = adminGetMachineResponses[keyof adminGetMachineResponses];

export type adminPatchMachineData = {
    body: MachinePatch;
    path: {
        /**
         * Machine Id
         */
        machine_id: string;
    };
    query?: never;
    url: '/admin/api/machines/{machine_id}';
};

export type adminPatchMachineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminPatchMachineError = adminPatchMachineErrors[keyof adminPatchMachineErrors];

export type adminPatchMachineResponses = {
    /**
     * Response Admin-Patch Machine
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminPatchMachineResponse = adminPatchMachineResponses[keyof adminPatchMachineResponses];

export type adminListDefinitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/definitions';
};

export type adminListDefinitionsResponses = {
    /**
     * Response Admin-List Definitions
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminListDefinitionsResponse = adminListDefinitionsResponses[keyof adminListDefinitionsResponses];

export type adminCreateDefinitionData = {
    body: DefinitionCreate;
    path?: never;
    query?: never;
    url: '/admin/api/definitions';
};

export type adminCreateDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateDefinitionError = adminCreateDefinitionErrors[keyof adminCreateDefinitionErrors];

export type adminCreateDefinitionResponses = {
    /**
     * Response Admin-Create Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminCreateDefinitionResponse = adminCreateDefinitionResponses[keyof adminCreateDefinitionResponses];

export type adminDeleteDefinitionData = {
    body?: never;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/admin/api/definitions/{definition_id}';
};

export type adminDeleteDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminDeleteDefinitionError = adminDeleteDefinitionErrors[keyof adminDeleteDefinitionErrors];

export type adminDeleteDefinitionResponses = {
    /**
     * Response Admin-Delete Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminDeleteDefinitionResponse = adminDeleteDefinitionResponses[keyof adminDeleteDefinitionResponses];

export type adminGetDefinitionData = {
    body?: never;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/admin/api/definitions/{definition_id}';
};

export type adminGetDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetDefinitionError = adminGetDefinitionErrors[keyof adminGetDefinitionErrors];

export type adminGetDefinitionResponses = {
    /**
     * Response Admin-Get Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetDefinitionResponse = adminGetDefinitionResponses[keyof adminGetDefinitionResponses];

export type adminPatchDefinitionData = {
    body: DefinitionPatch;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/admin/api/definitions/{definition_id}';
};

export type adminPatchDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminPatchDefinitionError = adminPatchDefinitionErrors[keyof adminPatchDefinitionErrors];

export type adminPatchDefinitionResponses = {
    /**
     * Response Admin-Patch Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminPatchDefinitionResponse = adminPatchDefinitionResponses[keyof adminPatchDefinitionResponses];

export type adminListInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/instances';
};

export type adminListInstancesResponses = {
    /**
     * Response Admin-List Instances
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type adminListInstancesResponse = adminListInstancesResponses[keyof adminListInstancesResponses];

export type adminGetInstanceData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}';
};

export type adminGetInstanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetInstanceError = adminGetInstanceErrors[keyof adminGetInstanceErrors];

export type adminGetInstanceResponses = {
    /**
     * Response Admin-Get Instance
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminGetInstanceResponse = adminGetInstanceResponses[keyof adminGetInstanceResponses];

export type adminClearCacheData = {
    /**
     * Body
     */
    body?: ActionBody | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/cache/clear';
};

export type adminClearCacheErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminClearCacheError = adminClearCacheErrors[keyof adminClearCacheErrors];

export type adminClearCacheResponses = {
    /**
     * Response Admin-Clear Cache
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminClearCacheResponse = adminClearCacheResponses[keyof adminClearCacheResponses];

export type adminPruneStorageData = {
    /**
     * Body
     */
    body?: ActionBody | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/admin/api/instances/{instance_id}/storage/prune';
};

export type adminPruneStorageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminPruneStorageError = adminPruneStorageErrors[keyof adminPruneStorageErrors];

export type adminPruneStorageResponses = {
    /**
     * Response Admin-Prune Storage
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminPruneStorageResponse = adminPruneStorageResponses[keyof adminPruneStorageResponses];

export type adminListResponsesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/admin/api/responses';
};

export type adminListResponsesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminListResponsesError = adminListResponsesErrors[keyof adminListResponsesErrors];

export type adminListResponsesResponses = {
    /**
     * Response Admin-List Responses
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminListResponsesResponse = adminListResponsesResponses[keyof adminListResponsesResponses];

export type adminUsageStatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/api/stats/usage';
};

export type adminUsageStatsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUsageStatsError = adminUsageStatsErrors[keyof adminUsageStatsErrors];

export type adminUsageStatsResponses = {
    /**
     * Response Admin-Usage Stats
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminUsageStatsResponse = adminUsageStatsResponses[keyof adminUsageStatsResponses];

export type adminOverviewStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/stats/overview';
};

export type adminOverviewStatsResponses = {
    /**
     * Response Admin-Overview Stats
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type adminOverviewStatsResponse = adminOverviewStatsResponses[keyof adminOverviewStatsResponses];

export type responsesCreateResponseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/responses';
};

export type responsesCreateResponseResponses = {
    /**
     * Response Responses-Create Response
     *
     * Successful Response
     */
    200: unknown;
};

export type chatCreateChatCompletionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/chat/completions';
};

export type chatCreateChatCompletionResponses = {
    /**
     * Response Chat-Create Chat Completion
     *
     * Successful Response
     */
    200: unknown;
};

export type modelsListModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type modelsListModelsResponses = {
    /**
     * Response Models-List Models
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type modelsListModelsResponse = modelsListModelsResponses[keyof modelsListModelsResponses];
