// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AgentListResponse
 */
export type AgentListResponse = {
    /**
     * Agents
     */
    agents: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * AgentRegisterRequest
 */
export type AgentRegisterRequest = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Platform
     */
    platform?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Host
     */
    host: string;
    /**
     * Port
     */
    port: number;
    /**
     * Gpu Info
     */
    gpu_info?: {
        [key: string]: unknown;
    } | null;
    /**
     * Running Server Ids
     */
    running_server_ids?: Array<string> | null;
};

/**
 * AgentRegisterResponse
 */
export type AgentRegisterResponse = {
    /**
     * Registered
     */
    registered: boolean;
    /**
     * Frontend Version
     */
    frontend_version: string;
};

/**
 * AgentUpdateRequest
 */
export type AgentUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Host
     */
    host?: string | null;
    /**
     * Port
     */
    port?: number | null;
};

/**
 * AllowedToolsChoice
 */
export type AllowedToolsChoice = {
    /**
     * Type
     */
    type?: 'allowed_tools';
    /**
     * Tools
     */
    tools: Array<SpecificFunctionChoice>;
    /**
     * Mode
     */
    mode?: 'none' | 'auto' | 'required';
};

/**
 * BatchData
 *
 * Batch data for OpenAI API response.
 */
export type BatchData = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object?: string;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Endpoint
     */
    endpoint: string;
    /**
     * Input File Id
     */
    input_file_id: string;
    /**
     * Output File Id
     */
    output_file_id?: string | null;
    /**
     * Results File Id
     */
    results_file_id?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Completion Window
     */
    completion_window: string;
    /**
     * Total Requests
     */
    total_requests?: number;
    /**
     * Processed Requests
     */
    processed_requests?: number;
    /**
     * Successful Requests
     */
    successful_requests?: number;
    /**
     * Failed Requests
     */
    failed_requests?: number;
    /**
     * Expires At
     */
    expires_at?: number | null;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * BatchRequest
 *
 * Batch creation request.
 */
export type BatchRequest = {
    /**
     * Input File Id
     */
    input_file_id: string;
    /**
     * Endpoint
     */
    endpoint: string;
    /**
     * Completion Window
     */
    completion_window?: string;
};

/**
 * BatchesList
 *
 * List of batches response.
 */
export type BatchesList = {
    /**
     * Object
     */
    object?: string;
    /**
     * Data
     */
    data: Array<BatchData>;
};

/**
 * BenchmarkDefinitionInput
 */
export type BenchmarkDefinitionInput = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Source Server Instance Id
     */
    source_server_instance_id?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * Body_v1/audio-create_transcription
 */
export type Body_v1_audio_create_transcription = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Model
     */
    model: string;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Response Format
     */
    response_format?: 'json' | 'text' | 'srt' | 'verbose_json';
    /**
     * Temperature
     */
    temperature?: number;
};

/**
 * Body_v1/audio-create_translation
 */
export type Body_v1_audio_create_translation = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Model
     */
    model: string;
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Response Format
     */
    response_format?: 'json' | 'text' | 'srt' | 'verbose_json';
    /**
     * Temperature
     */
    temperature?: number;
};

/**
 * Body_v1/files-upload_file
 */
export type Body_v1_files_upload_file = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Purpose
     */
    purpose: string;
};

/**
 * ChatCompletionRequest
 *
 * Chat completion request.
 */
export type ChatCompletionRequest = {
    /**
     * Model
     */
    model: string;
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Stream
     */
    stream?: boolean;
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * Max Tokens
     */
    max_tokens?: number | null;
    /**
     * Top P
     */
    top_p?: number | null;
    /**
     * Frequency Penalty
     */
    frequency_penalty?: number | null;
    /**
     * Presence Penalty
     */
    presence_penalty?: number | null;
    /**
     * Stop
     */
    stop?: string | Array<string> | null;
    /**
     * Tools
     */
    tools?: Array<Tool> | null;
    /**
     * Tool Choice
     */
    tool_choice?: string | {
        [key: string]: unknown;
    } | null;
    /**
     * Prompt Cache Options
     */
    prompt_cache_options?: {
        [key: string]: unknown;
    } | null;
    stream_options?: StreamOptions | null;
};

/**
 * ChatMessage
 *
 * Chat message (content may be null for assistant tool-call turns).
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: 'system' | 'user' | 'assistant' | 'developer' | 'tool';
    /**
     * Content
     */
    content?: string | null;
    /**
     * Reasoning Content
     */
    reasoning_content?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Tool Call Id
     */
    tool_call_id?: string | null;
    /**
     * Tool Calls
     */
    tool_calls?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * CompactRequestBody
 *
 * POST /v1/responses/compact request body (spec 2026-04-24).
 */
export type CompactRequestBody = {
    /**
     * Model
     */
    model: string;
    /**
     * Input
     */
    input: string | Array<({
        type: 'message';
    } & UserMessageItemParam) | ({
        type: 'reasoning';
    } & ReasoningItemParam) | ({
        type: 'function_call';
    } & FunctionCallItemParam) | ({
        type: 'function_call_output';
    } & FunctionCallOutputItemParam) | ({
        type: 'item_reference';
    } & ItemReferenceParam) | ({
        type: 'compaction';
    } & CompactionSummaryItemParam)>;
    /**
     * Previous Response Id
     */
    previous_response_id?: string | null;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Prompt Cache Key
     */
    prompt_cache_key?: string | null;
};

/**
 * CompactionSummaryItemParam
 */
export type CompactionSummaryItemParam = {
    /**
     * Type
     */
    type?: 'compaction';
    /**
     * Id
     */
    id: string;
    /**
     * Encrypted Content
     */
    encrypted_content: string;
};

/**
 * CompletionRequest
 *
 * Completion request for legacy /v1/completions endpoint.
 */
export type CompletionRequest = {
    /**
     * Model
     */
    model: string;
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Prompt
     */
    prompt: string | Array<string> | Array<number> | Array<Array<number>>;
    /**
     * Stream
     */
    stream?: boolean;
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * Max Tokens
     */
    max_tokens?: number | null;
    /**
     * Top P
     */
    top_p?: number | null;
    /**
     * Frequency Penalty
     */
    frequency_penalty?: number | null;
    /**
     * Presence Penalty
     */
    presence_penalty?: number | null;
    /**
     * Stop
     */
    stop?: string | Array<string> | null;
    /**
     * Echo
     */
    echo?: boolean;
    /**
     * N
     */
    n?: number;
    /**
     * Logprobs
     */
    logprobs?: number | null;
    /**
     * Suffix
     */
    suffix?: string | null;
    stream_options?: StreamOptions | null;
};

/**
 * CreateResponseBody
 *
 * POST /v1/responses request body.
 */
export type CreateResponseBody = {
    /**
     * Model
     */
    model: string;
    /**
     * Input
     */
    input: string | Array<({
        type: 'message';
    } & UserMessageItemParam) | ({
        type: 'reasoning';
    } & ReasoningItemParam) | ({
        type: 'function_call';
    } & FunctionCallItemParam) | ({
        type: 'function_call_output';
    } & FunctionCallOutputItemParam) | ({
        type: 'item_reference';
    } & ItemReferenceParam) | ({
        type: 'compaction';
    } & CompactionSummaryItemParam)>;
    /**
     * Previous Response Id
     */
    previous_response_id?: string | null;
    /**
     * Include
     */
    include?: Array<'reasoning.encrypted_content' | 'message.output_text.logprobs'>;
    /**
     * Tools
     */
    tools?: Array<FunctionToolParam>;
    /**
     * Tool Choice
     */
    tool_choice?: 'none' | 'auto' | 'required' | SpecificFunctionChoice | AllowedToolsChoice;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    };
    text?: TextParam | null;
    /**
     * Temperature
     */
    temperature?: number | null;
    /**
     * Top P
     */
    top_p?: number | null;
    /**
     * Presence Penalty
     */
    presence_penalty?: number | null;
    /**
     * Frequency Penalty
     */
    frequency_penalty?: number | null;
    /**
     * Parallel Tool Calls
     */
    parallel_tool_calls?: boolean | null;
    /**
     * Stream
     */
    stream?: boolean;
    stream_options?: StreamOptionsParam | null;
    /**
     * Background
     */
    background?: boolean;
    /**
     * Max Output Tokens
     */
    max_output_tokens?: number | null;
    /**
     * Max Tool Calls
     */
    max_tool_calls?: number | null;
    reasoning?: ReasoningParam | null;
    /**
     * Safety Identifier
     */
    safety_identifier?: string | null;
    /**
     * Prompt Cache Key
     */
    prompt_cache_key?: string | null;
    /**
     * Truncation
     */
    truncation?: 'auto' | 'disabled';
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Store
     */
    store?: boolean;
    /**
     * Service Tier
     */
    service_tier?: 'auto' | 'default' | 'flex' | 'priority';
    /**
     * Top Logprobs
     */
    top_logprobs?: number | null;
};

/**
 * DeleteFileResponse
 *
 * Delete file response.
 */
export type DeleteFileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object?: string;
    /**
     * Deleted
     */
    deleted: boolean;
};

/**
 * EmbeddingData
 *
 * Embedding data.
 */
export type EmbeddingData = {
    /**
     * Object
     */
    object?: string;
    /**
     * Embedding
     */
    embedding: Array<number>;
    /**
     * Index
     */
    index: number;
};

/**
 * EmbeddingRequest
 *
 * Embedding request.
 */
export type EmbeddingRequest = {
    /**
     * Model
     */
    model: string;
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Input
     *
     * Input text or list of texts
     */
    input: string | Array<string>;
    /**
     * Encoding Format
     */
    encoding_format?: 'float' | 'base64';
};

/**
 * EmbeddingResponse
 *
 * Embedding response.
 */
export type EmbeddingResponse = {
    /**
     * Object
     */
    object?: string;
    /**
     * Data
     */
    data: Array<EmbeddingData>;
    /**
     * Model
     */
    model: string;
    usage: EmbeddingUsage;
};

/**
 * EmbeddingUsage
 *
 * Embedding usage.
 */
export type EmbeddingUsage = {
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Total Tokens
     */
    total_tokens: number;
};

/**
 * FileData
 *
 * File data for OpenAI API response.
 */
export type FileData = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object?: string;
    /**
     * Bytes
     */
    bytes: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Filename
     */
    filename: string;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Status
     */
    status: string;
};

/**
 * FilesList
 *
 * List of files response.
 */
export type FilesList = {
    /**
     * Object
     */
    object?: string;
    /**
     * Data
     */
    data: Array<FileData>;
};

/**
 * FunctionCallItemParam
 */
export type FunctionCallItemParam = {
    /**
     * Type
     */
    type?: 'function_call';
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Arguments
     */
    arguments: string;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Status
     */
    status?: 'in_progress' | 'completed' | 'incomplete' | null;
};

/**
 * FunctionCallOutputItemParam
 */
export type FunctionCallOutputItemParam = {
    /**
     * Type
     */
    type?: 'function_call_output';
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Output
     */
    output: string | Array<({
        type: 'input_text';
    } & InputTextContent) | ({
        type: 'input_image';
    } & InputImageContent) | ({
        type: 'input_file';
    } & InputFileContent) | ({
        type: 'input_video';
    } & InputVideoContent)>;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Status
     */
    status?: 'in_progress' | 'completed' | 'incomplete' | null;
};

/**
 * FunctionToolParam
 *
 * Flat function tool definition (Responses API shape).
 */
export type FunctionToolParam = {
    /**
     * Type
     */
    type?: 'function';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: unknown;
    } | null;
    /**
     * Strict
     */
    strict?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InputFileContent
 *
 * A file input to the model.
 */
export type InputFileContent = {
    /**
     * Type
     */
    type?: 'input_file';
    /**
     * Filename
     */
    filename?: string | null;
    /**
     * File Data
     */
    file_data?: string | null;
    /**
     * File Url
     */
    file_url?: string | null;
};

/**
 * InputImageContent
 *
 * An image input to the model.
 */
export type InputImageContent = {
    /**
     * Type
     */
    type?: 'input_image';
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Detail
     */
    detail?: 'low' | 'high' | 'auto';
};

/**
 * InputTextContent
 *
 * A text input to the model.
 */
export type InputTextContent = {
    /**
     * Type
     */
    type?: 'input_text';
    /**
     * Text
     */
    text: string;
};

/**
 * InputVideoContent
 *
 * A video input to the model.
 */
export type InputVideoContent = {
    /**
     * Type
     */
    type?: 'input_video';
    /**
     * Video Url
     */
    video_url: string;
};

/**
 * ItemReferenceParam
 */
export type ItemReferenceParam = {
    /**
     * Type
     */
    type?: 'item_reference';
    /**
     * Id
     */
    id: string;
};

/**
 * JsonObjectResponseFormat
 */
export type JsonObjectResponseFormat = {
    /**
     * Type
     */
    type?: 'json_object';
};

/**
 * JsonSchemaResponseFormat
 */
export type JsonSchemaResponseFormat = {
    /**
     * Type
     */
    type?: 'json_schema';
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Schema
     */
    schema?: {
        [key: string]: unknown;
    } | null;
    /**
     * Strict
     */
    strict?: boolean | null;
};

/**
 * Message
 *
 * Generic message response.
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * Model
 */
export type Model = {
    /**
     * Id
     */
    id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Model Type
     */
    model_type?: string;
    /**
     * Parameter Count
     */
    parameter_count?: number | null;
    /**
     * Quantization
     */
    quantization: string;
    /**
     * Supports Embeddings
     */
    supports_embeddings?: boolean;
    /**
     * Supports Vision
     */
    supports_vision?: boolean;
    /**
     * License
     */
    license?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Source
     */
    source: string;
    /**
     * Source Repo Id
     */
    source_repo_id?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Source File
     */
    source_file?: string | null;
    /**
     * Downloaded At
     */
    downloaded_at?: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * ModelCreate
 *
 * Model creation model.
 */
export type ModelCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Model Type
     */
    model_type?: string;
    /**
     * Parameter Count
     */
    parameter_count?: number | null;
    /**
     * Quantization
     */
    quantization: string;
    /**
     * Supports Embeddings
     */
    supports_embeddings?: boolean;
    /**
     * Supports Vision
     */
    supports_vision?: boolean;
    /**
     * License
     */
    license?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Source
     */
    source: string;
    /**
     * Source Repo Id
     */
    source_repo_id?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Source File
     */
    source_file?: string | null;
};

/**
 * ModelData
 *
 * Model data for OpenAI API response.
 */
export type ModelData = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object?: string;
    /**
     * Created
     */
    created: number;
    /**
     * Owned By
     */
    owned_by?: string;
};

/**
 * ModelUpdate
 *
 * Model update model.
 */
export type ModelUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Path
     */
    path?: string | null;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Architecture
     */
    architecture?: string | null;
    /**
     * Model Type
     */
    model_type?: string | null;
    /**
     * Parameter Count
     */
    parameter_count?: number | null;
    /**
     * Quantization
     */
    quantization?: string | null;
    /**
     * Supports Embeddings
     */
    supports_embeddings?: boolean | null;
    /**
     * Supports Vision
     */
    supports_vision?: boolean | null;
    /**
     * License
     */
    license?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Source Repo Id
     */
    source_repo_id?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Source File
     */
    source_file?: string | null;
};

/**
 * ModelsList
 *
 * List of models response.
 */
export type ModelsList = {
    /**
     * Object
     */
    object?: string;
    /**
     * Data
     */
    data: Array<ModelData>;
};

/**
 * OutputTextContentParam
 */
export type OutputTextContentParam = {
    /**
     * Type
     */
    type?: 'output_text';
    /**
     * Text
     */
    text: string;
    /**
     * Annotations
     */
    annotations?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ReasoningItemParam
 */
export type ReasoningItemParam = {
    /**
     * Type
     */
    type?: 'reasoning';
    /**
     * Summary
     */
    summary?: Array<ReasoningSummaryContentParam>;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Content
     */
    content?: Array<ReasoningTextContent> | null;
    /**
     * Encrypted Content
     */
    encrypted_content?: string | null;
    /**
     * Status
     */
    status?: 'in_progress' | 'completed' | 'incomplete' | null;
};

/**
 * ReasoningParam
 */
export type ReasoningParam = {
    /**
     * Effort
     */
    effort?: 'none' | 'low' | 'medium' | 'high' | 'xhigh' | null;
    /**
     * Summary
     */
    summary?: 'concise' | 'detailed' | 'auto' | null;
};

/**
 * ReasoningSummaryContentParam
 */
export type ReasoningSummaryContentParam = {
    /**
     * Type
     */
    type?: 'summary_text';
    /**
     * Text
     */
    text: string;
};

/**
 * ReasoningTextContent
 *
 * Raw reasoning text content.
 */
export type ReasoningTextContent = {
    /**
     * Type
     */
    type?: 'reasoning_text';
    /**
     * Text
     */
    text: string;
};

/**
 * RefusalContentParam
 */
export type RefusalContentParam = {
    /**
     * Type
     */
    type?: 'refusal';
    /**
     * Refusal
     */
    refusal: string;
};

/**
 * RunInput
 */
export type RunInput = {
    /**
     * Definition Id
     */
    definition_id: string;
};

/**
 * ServerInstanceListResponse
 */
export type ServerInstanceListResponse = {
    /**
     * Server Instances
     */
    server_instances: Array<ServerInstanceResponse>;
};

/**
 * ServerInstanceResponse
 */
export type ServerInstanceResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Model Name
     */
    model_name?: string | null;
    /**
     * Mmproj Model Id
     */
    mmproj_model_id?: string | null;
    /**
     * Mmproj Model Name
     */
    mmproj_model_name?: string | null;
    /**
     * Dflash Model Id
     */
    dflash_model_id?: string | null;
    /**
     * Dflash Model Name
     */
    dflash_model_name?: string | null;
    /**
     * Alias
     */
    alias: string;
    /**
     * Status
     */
    status: string;
    /**
     * Health Status
     */
    health_status: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Agent Name
     */
    agent_name?: string | null;
    /**
     * Agent Host
     */
    agent_host?: string | null;
    /**
     * Agent Port
     */
    agent_port?: number | null;
    /**
     * Proxy Url
     */
    proxy_url?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Total Requests
     */
    total_requests: number;
    /**
     * Cpu Usage Percent
     */
    cpu_usage_percent?: number | null;
    /**
     * Ram Usage Bytes
     */
    ram_usage_bytes?: number | null;
    /**
     * Vram Usage Bytes
     */
    vram_usage_bytes?: number | null;
    /**
     * Gpu Layers
     */
    gpu_layers?: number;
    /**
     * Context Size
     */
    context_size?: number;
    /**
     * Flash Attn
     */
    flash_attn?: boolean;
    /**
     * Mtp Draft Max
     */
    mtp_draft_max?: number | null;
    /**
     * Inactivity Timeout Seconds
     */
    inactivity_timeout_seconds?: number;
    /**
     * Server Options
     */
    server_options?: {
        [key: string]: unknown;
    };
};

/**
 * ServerOptions
 *
 * Core llama-server options exposed by the UI.
 *
 * None means that llama.cpp should use its own default and the agent omits
 * the corresponding command-line flag.
 */
export type ServerOptions = {
    /**
     * Threads
     */
    threads?: number | null;
    /**
     * Threads Batch
     */
    threads_batch?: number | null;
    /**
     * Batch Size
     */
    batch_size?: number | null;
    /**
     * Ubatch Size
     */
    ubatch_size?: number | null;
    /**
     * Keep
     */
    keep?: number | null;
    /**
     * Predict
     */
    predict?: number | null;
    /**
     * Swa Full
     */
    swa_full?: boolean | null;
    /**
     * Cache Type K
     */
    cache_type_k?: 'f32' | 'f16' | 'bf16' | 'q8_0' | 'q4_0' | 'q4_1' | 'iq4_nl' | 'q5_0' | 'q5_1' | 'turbo4' | null;
    /**
     * Cache Type V
     */
    cache_type_v?: 'f32' | 'f16' | 'bf16' | 'q8_0' | 'q4_0' | 'q4_1' | 'iq4_nl' | 'q5_0' | 'q5_1' | 'turbo4' | null;
    /**
     * Kv Offload
     */
    kv_offload?: boolean | null;
    /**
     * Cache Prompt
     */
    cache_prompt?: boolean | null;
    /**
     * Cache Reuse
     */
    cache_reuse?: number | null;
    /**
     * Ctx Checkpoints
     */
    ctx_checkpoints?: number | null;
    /**
     * Checkpoint Every
     */
    checkpoint_every?: number | null;
    /**
     * Cache Ram
     */
    cache_ram?: number | null;
    /**
     * Slot Save Path
     */
    slot_save_path?: string | null;
    /**
     * Gpu Layers
     */
    gpu_layers?: number | string | null;
    /**
     * Device
     */
    device?: string | null;
    /**
     * Split Mode
     */
    split_mode?: 'none' | 'layer' | 'row' | 'tensor' | null;
    /**
     * Tensor Split
     */
    tensor_split?: string | null;
    /**
     * Main Gpu
     */
    main_gpu?: number | null;
    /**
     * Fit
     */
    fit?: 'on' | 'off' | null;
    /**
     * Fit Target
     */
    fit_target?: string | null;
    /**
     * Fit Ctx
     */
    fit_ctx?: number | null;
    /**
     * Temperature
     */
    temperature?: number | null;
    /**
     * Top K
     */
    top_k?: number | null;
    /**
     * Top P
     */
    top_p?: number | null;
    /**
     * Min P
     */
    min_p?: number | null;
    /**
     * Repeat Penalty
     */
    repeat_penalty?: number | null;
    /**
     * Presence Penalty
     */
    presence_penalty?: number | null;
    /**
     * Frequency Penalty
     */
    frequency_penalty?: number | null;
    /**
     * Seed
     */
    seed?: number | null;
    /**
     * Parallel
     */
    parallel?: number | null;
    /**
     * Reasoning
     */
    reasoning?: 'on' | 'off' | 'auto' | null;
    /**
     * Reasoning Budget
     */
    reasoning_budget?: number | null;
    /**
     * Spec Draft P Min
     */
    spec_draft_p_min?: number | null;
    /**
     * Strict Mtp Qwen
     */
    strict_mtp_qwen?: boolean | null;
    /**
     * Kv Unified
     */
    kv_unified?: boolean | null;
    /**
     * No Mmap
     */
    no_mmap?: boolean | null;
    /**
     * No Cache Idle Slots
     */
    no_cache_idle_slots?: boolean | null;
    /**
     * Cont Batching
     */
    cont_batching?: boolean | null;
    /**
     * Warmup
     */
    warmup?: boolean | null;
    /**
     * Context Shift
     */
    context_shift?: boolean | null;
    /**
     * Jinja
     */
    jinja?: boolean | null;
};

/**
 * SpecificFunctionChoice
 */
export type SpecificFunctionChoice = {
    /**
     * Type
     */
    type?: 'function';
    /**
     * Name
     */
    name: string;
};

/**
 * SpeechRequest
 *
 * Speech generation request.
 */
export type SpeechRequest = {
    /**
     * Model
     */
    model: string;
    /**
     * Input
     */
    input: string;
    /**
     * Voice
     */
    voice?: string;
    /**
     * Response Format
     */
    response_format?: 'mp3' | 'wav' | 'flac' | 'opus' | 'aac';
    /**
     * Speed
     */
    speed?: number;
};

/**
 * StartServerRequest
 */
export type StartServerRequest = {
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Gpu Layers
     */
    gpu_layers?: number;
    /**
     * Context Size
     */
    context_size?: number;
    /**
     * Mmproj Model Id
     */
    mmproj_model_id?: string | null;
    /**
     * Dflash Model Id
     */
    dflash_model_id?: string | null;
    /**
     * Mtp Draft Max
     */
    mtp_draft_max?: number | null;
    server_options?: ServerOptions;
    /**
     * Alias
     */
    alias: string;
};

/**
 * StreamOptions
 *
 * OpenAI stream_options (include_usage emits a final usage chunk).
 */
export type StreamOptions = {
    /**
     * Include Usage
     */
    include_usage?: boolean;
};

/**
 * StreamOptionsParam
 */
export type StreamOptionsParam = {
    /**
     * Include Obfuscation
     */
    include_obfuscation?: boolean;
};

/**
 * TextParam
 */
export type TextParam = {
    /**
     * Format
     */
    format?: ({
        type: 'text';
    } & TextResponseFormat) | ({
        type: 'json_object';
    } & JsonObjectResponseFormat) | ({
        type: 'json_schema';
    } & JsonSchemaResponseFormat) | null;
    /**
     * Verbosity
     */
    verbosity?: 'low' | 'medium' | 'high' | null;
};

/**
 * TextResponseFormat
 */
export type TextResponseFormat = {
    /**
     * Type
     */
    type?: 'text';
};

/**
 * Tool
 *
 * OpenAI tool definition ({"type": "function", "function": {...}}).
 */
export type Tool = {
    /**
     * Type
     */
    type?: string;
    function: ToolFunction;
};

/**
 * ToolFunction
 *
 * OpenAI tool function definition.
 */
export type ToolFunction = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: unknown;
    };
};

/**
 * TranscriptionResponse
 *
 * Transcription response.
 */
export type TranscriptionResponse = {
    /**
     * Text
     */
    text: string;
};

/**
 * TranslationResponse
 *
 * Translation response.
 */
export type TranslationResponse = {
    /**
     * Text
     */
    text: string;
};

/**
 * UpdateServerRequest
 *
 * Editable server settings. All fields optional.
 */
export type UpdateServerRequest = {
    /**
     * Alias
     */
    alias?: string | null;
    /**
     * Model Id
     */
    model_id?: string | null;
    /**
     * Gpu Layers
     */
    gpu_layers?: number | null;
    /**
     * Context Size
     */
    context_size?: number | null;
    /**
     * Flash Attn
     */
    flash_attn?: boolean | null;
    /**
     * Mtp Draft Max
     */
    mtp_draft_max?: number | null;
    /**
     * Inactivity Timeout Seconds
     */
    inactivity_timeout_seconds?: number | null;
    /**
     * Mmproj Model Id
     */
    mmproj_model_id?: string | null;
    /**
     * Dflash Model Id
     */
    dflash_model_id?: string | null;
    server_options?: ServerOptions | null;
    /**
     * Restart
     */
    restart?: boolean;
};

/**
 * UserMessageItemParam
 */
export type UserMessageItemParam = {
    /**
     * Type
     */
    type?: 'message';
    /**
     * Role
     */
    role?: 'user' | 'assistant' | 'system' | 'developer';
    /**
     * Content
     */
    content: string | Array<({
        type: 'input_text';
    } & InputTextContent) | ({
        type: 'input_image';
    } & InputImageContent) | ({
        type: 'input_file';
    } & InputFileContent) | ({
        type: 'input_video';
    } & InputVideoContent) | OutputTextContentParam | RefusalContentParam>;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Status
     */
    status?: 'in_progress' | 'completed' | 'incomplete' | null;
    /**
     * Phase
     */
    phase?: 'commentary' | 'final_answer' | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type agentsRegisterAgentData = {
    body: AgentRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agents/register';
};

export type agentsRegisterAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsRegisterAgentError = agentsRegisterAgentErrors[keyof agentsRegisterAgentErrors];

export type agentsRegisterAgentResponses = {
    /**
     * Successful Response
     */
    200: AgentRegisterResponse;
};

export type agentsRegisterAgentResponse = agentsRegisterAgentResponses[keyof agentsRegisterAgentResponses];

export type agentsListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agents';
};

export type agentsListAgentsResponses = {
    /**
     * Successful Response
     */
    200: AgentListResponse;
};

export type agentsListAgentsResponse = agentsListAgentsResponses[keyof agentsListAgentsResponses];

export type agentsDeleteAgentData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/agents/{agent_id}';
};

export type agentsDeleteAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsDeleteAgentError = agentsDeleteAgentErrors[keyof agentsDeleteAgentErrors];

export type agentsDeleteAgentResponses = {
    /**
     * Response Agents-Delete Agent
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type agentsDeleteAgentResponse = agentsDeleteAgentResponses[keyof agentsDeleteAgentResponses];

export type agentsGetAgentData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/agents/{agent_id}';
};

export type agentsGetAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsGetAgentError = agentsGetAgentErrors[keyof agentsGetAgentErrors];

export type agentsGetAgentResponses = {
    /**
     * Response Agents-Get Agent
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type agentsGetAgentResponse = agentsGetAgentResponses[keyof agentsGetAgentResponses];

export type agentsUpdateAgentData = {
    body: AgentUpdateRequest;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/agents/{agent_id}';
};

export type agentsUpdateAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsUpdateAgentError = agentsUpdateAgentErrors[keyof agentsUpdateAgentErrors];

export type agentsUpdateAgentResponses = {
    /**
     * Response Agents-Update Agent
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type agentsUpdateAgentResponse = agentsUpdateAgentResponses[keyof agentsUpdateAgentResponses];

export type agentsSendCommandData = {
    /**
     * Command
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/agents/{agent_id}/command';
};

export type agentsSendCommandErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsSendCommandError = agentsSendCommandErrors[keyof agentsSendCommandErrors];

export type agentsSendCommandResponses = {
    /**
     * Response Agents-Send Command
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type agentsSendCommandResponse = agentsSendCommandResponses[keyof agentsSendCommandResponses];

export type metricsMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/metrics';
};

export type metricsMetricsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type serverInstancesListServerInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/server-instances';
};

export type serverInstancesListServerInstancesResponses = {
    /**
     * Successful Response
     */
    200: ServerInstanceListResponse;
};

export type serverInstancesListServerInstancesResponse = serverInstancesListServerInstancesResponses[keyof serverInstancesListServerInstancesResponses];

export type serverInstancesDeleteServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/server-instances/{server_id}';
};

export type serverInstancesDeleteServerErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type serverInstancesDeleteServerError = serverInstancesDeleteServerErrors[keyof serverInstancesDeleteServerErrors];

export type serverInstancesDeleteServerResponses = {
    /**
     * Response Server-Instances-Delete Server
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type serverInstancesDeleteServerResponse = serverInstancesDeleteServerResponses[keyof serverInstancesDeleteServerResponses];

export type serverInstancesGetServerInstanceData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/server-instances/{server_id}';
};

export type serverInstancesGetServerInstanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type serverInstancesGetServerInstanceError = serverInstancesGetServerInstanceErrors[keyof serverInstancesGetServerInstanceErrors];

export type serverInstancesGetServerInstanceResponses = {
    /**
     * Successful Response
     */
    200: ServerInstanceResponse;
};

export type serverInstancesGetServerInstanceResponse = serverInstancesGetServerInstanceResponses[keyof serverInstancesGetServerInstanceResponses];

export type serverInstancesUpdateServerData = {
    body: UpdateServerRequest;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/server-instances/{server_id}';
};

export type serverInstancesUpdateServerErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type serverInstancesUpdateServerError = serverInstancesUpdateServerErrors[keyof serverInstancesUpdateServerErrors];

export type serverInstancesUpdateServerResponses = {
    /**
     * Response Server-Instances-Update Server
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type serverInstancesUpdateServerResponse = serverInstancesUpdateServerResponses[keyof serverInstancesUpdateServerResponses];

export type serverInstancesStartServerData = {
    body: StartServerRequest;
    path?: never;
    query?: never;
    url: '/api/v1/server-instances/start';
};

export type serverInstancesStartServerErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type serverInstancesStartServerError = serverInstancesStartServerErrors[keyof serverInstancesStartServerErrors];

export type serverInstancesStartServerResponses = {
    /**
     * Response Server-Instances-Start Server
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type serverInstancesStartServerResponse = serverInstancesStartServerResponses[keyof serverInstancesStartServerResponses];

export type serverInstancesRestartServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/server-instances/{server_id}/start';
};

export type serverInstancesRestartServerErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type serverInstancesRestartServerError = serverInstancesRestartServerErrors[keyof serverInstancesRestartServerErrors];

export type serverInstancesRestartServerResponses = {
    /**
     * Response Server-Instances-Restart Server
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type serverInstancesRestartServerResponse = serverInstancesRestartServerResponses[keyof serverInstancesRestartServerResponses];

export type serverInstancesStopServerData = {
    body?: never;
    path: {
        /**
         * Server Id
         */
        server_id: string;
    };
    query?: never;
    url: '/api/v1/server-instances/{server_id}/stop';
};

export type serverInstancesStopServerErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type serverInstancesStopServerError = serverInstancesStopServerErrors[keyof serverInstancesStopServerErrors];

export type serverInstancesStopServerResponses = {
    /**
     * Response Server-Instances-Stop Server
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type serverInstancesStopServerResponse = serverInstancesStopServerResponses[keyof serverInstancesStopServerResponses];

export type benchmarksListDefinitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/benchmarks/definitions';
};

export type benchmarksListDefinitionsResponses = {
    /**
     * Response Benchmarks-List Definitions
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type benchmarksListDefinitionsResponse = benchmarksListDefinitionsResponses[keyof benchmarksListDefinitionsResponses];

export type benchmarksCreateDefinitionData = {
    body: BenchmarkDefinitionInput;
    path?: never;
    query?: never;
    url: '/api/v1/benchmarks/definitions';
};

export type benchmarksCreateDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksCreateDefinitionError = benchmarksCreateDefinitionErrors[keyof benchmarksCreateDefinitionErrors];

export type benchmarksCreateDefinitionResponses = {
    /**
     * Response Benchmarks-Create Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type benchmarksCreateDefinitionResponse = benchmarksCreateDefinitionResponses[keyof benchmarksCreateDefinitionResponses];

export type benchmarksDeleteDefinitionData = {
    body?: never;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/api/v1/benchmarks/definitions/{definition_id}';
};

export type benchmarksDeleteDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksDeleteDefinitionError = benchmarksDeleteDefinitionErrors[keyof benchmarksDeleteDefinitionErrors];

export type benchmarksDeleteDefinitionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type benchmarksDeleteDefinitionResponse = benchmarksDeleteDefinitionResponses[keyof benchmarksDeleteDefinitionResponses];

export type benchmarksUpdateDefinitionData = {
    body: BenchmarkDefinitionInput;
    path: {
        /**
         * Definition Id
         */
        definition_id: string;
    };
    query?: never;
    url: '/api/v1/benchmarks/definitions/{definition_id}';
};

export type benchmarksUpdateDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksUpdateDefinitionError = benchmarksUpdateDefinitionErrors[keyof benchmarksUpdateDefinitionErrors];

export type benchmarksUpdateDefinitionResponses = {
    /**
     * Response Benchmarks-Update Definition
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type benchmarksUpdateDefinitionResponse = benchmarksUpdateDefinitionResponses[keyof benchmarksUpdateDefinitionResponses];

export type benchmarksListRunsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/benchmarks/runs';
};

export type benchmarksListRunsResponses = {
    /**
     * Response Benchmarks-List Runs
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type benchmarksListRunsResponse = benchmarksListRunsResponses[keyof benchmarksListRunsResponses];

export type benchmarksCreateRunData = {
    body: RunInput;
    path?: never;
    query?: never;
    url: '/api/v1/benchmarks/runs';
};

export type benchmarksCreateRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksCreateRunError = benchmarksCreateRunErrors[keyof benchmarksCreateRunErrors];

export type benchmarksCreateRunResponses = {
    /**
     * Response Benchmarks-Create Run
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type benchmarksCreateRunResponse = benchmarksCreateRunResponses[keyof benchmarksCreateRunResponses];

export type benchmarksGetResultsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/benchmarks/runs/{run_id}/results';
};

export type benchmarksGetResultsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksGetResultsError = benchmarksGetResultsErrors[keyof benchmarksGetResultsErrors];

export type benchmarksGetResultsResponses = {
    /**
     * Response Benchmarks-Get Results
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    } | null;
};

export type benchmarksGetResultsResponse = benchmarksGetResultsResponses[keyof benchmarksGetResultsResponses];

export type benchmarksCancelRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/benchmarks/runs/{run_id}/cancel';
};

export type benchmarksCancelRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksCancelRunError = benchmarksCancelRunErrors[keyof benchmarksCancelRunErrors];

export type benchmarksCancelRunResponses = {
    /**
     * Response Benchmarks-Cancel Run
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type benchmarksCancelRunResponse = benchmarksCancelRunResponses[keyof benchmarksCancelRunResponses];

export type benchmarksAbortRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/benchmarks/runs/{run_id}/abort';
};

export type benchmarksAbortRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksAbortRunError = benchmarksAbortRunErrors[keyof benchmarksAbortRunErrors];

export type benchmarksAbortRunResponses = {
    /**
     * Response Benchmarks-Abort Run
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type benchmarksAbortRunResponse = benchmarksAbortRunResponses[keyof benchmarksAbortRunResponses];

export type benchmarksForceStopRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/benchmarks/runs/{run_id}/force-stop';
};

export type benchmarksForceStopRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type benchmarksForceStopRunError = benchmarksForceStopRunErrors[keyof benchmarksForceStopRunErrors];

export type benchmarksForceStopRunResponses = {
    /**
     * Response Benchmarks-Force Stop Run
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type benchmarksForceStopRunResponse = benchmarksForceStopRunResponses[keyof benchmarksForceStopRunResponses];

export type modelsReadModelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/models/';
};

export type modelsReadModelsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelsReadModelsError = modelsReadModelsErrors[keyof modelsReadModelsErrors];

export type modelsReadModelsResponses = {
    /**
     * Response Models-Read Models
     *
     * Successful Response
     */
    200: Array<Model>;
};

export type modelsReadModelsResponse = modelsReadModelsResponses[keyof modelsReadModelsResponses];

export type modelsCreateModelData = {
    body: ModelCreate;
    path?: never;
    query?: never;
    url: '/api/v1/models/';
};

export type modelsCreateModelErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelsCreateModelError = modelsCreateModelErrors[keyof modelsCreateModelErrors];

export type modelsCreateModelResponses = {
    /**
     * Successful Response
     */
    200: Model;
};

export type modelsCreateModelResponse = modelsCreateModelResponses[keyof modelsCreateModelResponses];

export type modelsDeleteModelData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/models/{id}';
};

export type modelsDeleteModelErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelsDeleteModelError = modelsDeleteModelErrors[keyof modelsDeleteModelErrors];

export type modelsDeleteModelResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type modelsDeleteModelResponse = modelsDeleteModelResponses[keyof modelsDeleteModelResponses];

export type modelsReadModelData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/models/{id}';
};

export type modelsReadModelErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelsReadModelError = modelsReadModelErrors[keyof modelsReadModelErrors];

export type modelsReadModelResponses = {
    /**
     * Successful Response
     */
    200: Model;
};

export type modelsReadModelResponse = modelsReadModelResponses[keyof modelsReadModelResponses];

export type modelsUpdateModelData = {
    body: ModelUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/models/{id}';
};

export type modelsUpdateModelErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelsUpdateModelError = modelsUpdateModelErrors[keyof modelsUpdateModelErrors];

export type modelsUpdateModelResponses = {
    /**
     * Successful Response
     */
    200: Model;
};

export type modelsUpdateModelResponse = modelsUpdateModelResponses[keyof modelsUpdateModelResponses];

export type huggingfaceSearchModelsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search
         *
         * Search query
         */
        search: string;
        /**
         * Limit
         *
         * Max results
         */
        limit?: number;
        /**
         * Full
         *
         * Include full model info
         */
        full?: boolean;
    };
    url: '/api/v1/huggingface/search';
};

export type huggingfaceSearchModelsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type huggingfaceSearchModelsError = huggingfaceSearchModelsErrors[keyof huggingfaceSearchModelsErrors];

export type huggingfaceSearchModelsResponses = {
    /**
     * Response Huggingface-Search Models
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type huggingfaceSearchModelsResponse = huggingfaceSearchModelsResponses[keyof huggingfaceSearchModelsResponses];

export type huggingfaceListModelFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repo Id
         *
         * HuggingFace repository ID (e.g., 'unsloth/Qwen3.8-27B-GGUF')
         */
        repo_id: string;
    };
    url: '/api/v1/huggingface/models/files';
};

export type huggingfaceListModelFilesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type huggingfaceListModelFilesError = huggingfaceListModelFilesErrors[keyof huggingfaceListModelFilesErrors];

export type huggingfaceListModelFilesResponses = {
    /**
     * Response Huggingface-List Model Files
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type huggingfaceListModelFilesResponse = huggingfaceListModelFilesResponses[keyof huggingfaceListModelFilesResponses];

export type huggingfaceGetModelInfoData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repo Id
         *
         * HuggingFace repository ID
         */
        repo_id: string;
    };
    url: '/api/v1/huggingface/models/info';
};

export type huggingfaceGetModelInfoErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type huggingfaceGetModelInfoError = huggingfaceGetModelInfoErrors[keyof huggingfaceGetModelInfoErrors];

export type huggingfaceGetModelInfoResponses = {
    /**
     * Response Huggingface-Get Model Info
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type huggingfaceGetModelInfoResponse = huggingfaceGetModelInfoResponses[keyof huggingfaceGetModelInfoResponses];

export type huggingfaceGetParameterCountData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repo Id
         *
         * HuggingFace repository ID
         */
        repo_id: string;
    };
    url: '/api/v1/huggingface/models/params';
};

export type huggingfaceGetParameterCountErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type huggingfaceGetParameterCountError = huggingfaceGetParameterCountErrors[keyof huggingfaceGetParameterCountErrors];

export type huggingfaceGetParameterCountResponses = {
    /**
     * Response Huggingface-Get Parameter Count
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type huggingfaceGetParameterCountResponse = huggingfaceGetParameterCountResponses[keyof huggingfaceGetParameterCountResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type v1ModelsListModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type v1ModelsListModelsResponses = {
    /**
     * Successful Response
     */
    200: ModelsList;
};

export type v1ModelsListModelsResponse = v1ModelsListModelsResponses[keyof v1ModelsListModelsResponses];

export type v1ModelsRetrieveModelData = {
    body?: never;
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/v1/models/{model_id}';
};

export type v1ModelsRetrieveModelErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1ModelsRetrieveModelError = v1ModelsRetrieveModelErrors[keyof v1ModelsRetrieveModelErrors];

export type v1ModelsRetrieveModelResponses = {
    /**
     * Successful Response
     */
    200: ModelData;
};

export type v1ModelsRetrieveModelResponse = v1ModelsRetrieveModelResponses[keyof v1ModelsRetrieveModelResponses];

export type v1ChatCreateChatCompletionData = {
    body: ChatCompletionRequest;
    path?: never;
    query?: never;
    url: '/v1/chat/completions';
};

export type v1ChatCreateChatCompletionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1ChatCreateChatCompletionError = v1ChatCreateChatCompletionErrors[keyof v1ChatCreateChatCompletionErrors];

export type v1ChatCreateChatCompletionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type v1CompletionsCreateCompletionData = {
    body: CompletionRequest;
    path?: never;
    query?: never;
    url: '/v1/completions';
};

export type v1CompletionsCreateCompletionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1CompletionsCreateCompletionError = v1CompletionsCreateCompletionErrors[keyof v1CompletionsCreateCompletionErrors];

export type v1CompletionsCreateCompletionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type v1EmbeddingsCreateEmbeddingData = {
    body: EmbeddingRequest;
    path?: never;
    query?: never;
    url: '/v1/embeddings';
};

export type v1EmbeddingsCreateEmbeddingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1EmbeddingsCreateEmbeddingError = v1EmbeddingsCreateEmbeddingErrors[keyof v1EmbeddingsCreateEmbeddingErrors];

export type v1EmbeddingsCreateEmbeddingResponses = {
    /**
     * Successful Response
     */
    200: EmbeddingResponse;
};

export type v1EmbeddingsCreateEmbeddingResponse = v1EmbeddingsCreateEmbeddingResponses[keyof v1EmbeddingsCreateEmbeddingResponses];

export type v1ResponsesCreateResponseData = {
    body: CreateResponseBody;
    path?: never;
    query?: never;
    url: '/v1/responses';
};

export type v1ResponsesCreateResponseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1ResponsesCreateResponseError = v1ResponsesCreateResponseErrors[keyof v1ResponsesCreateResponseErrors];

export type v1ResponsesCreateResponseResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type v1ResponsesCompactResponseData = {
    body: CompactRequestBody;
    path?: never;
    query?: never;
    url: '/v1/responses/compact';
};

export type v1ResponsesCompactResponseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1ResponsesCompactResponseError = v1ResponsesCompactResponseErrors[keyof v1ResponsesCompactResponseErrors];

export type v1ResponsesCompactResponseResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type v1FilesListFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Purpose
         */
        purpose?: string | null;
    };
    url: '/v1/files';
};

export type v1FilesListFilesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1FilesListFilesError = v1FilesListFilesErrors[keyof v1FilesListFilesErrors];

export type v1FilesListFilesResponses = {
    /**
     * Successful Response
     */
    200: FilesList;
};

export type v1FilesListFilesResponse = v1FilesListFilesResponses[keyof v1FilesListFilesResponses];

export type v1FilesUploadFileData = {
    body: Body_v1_files_upload_file;
    path?: never;
    query?: never;
    url: '/v1/files';
};

export type v1FilesUploadFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1FilesUploadFileError = v1FilesUploadFileErrors[keyof v1FilesUploadFileErrors];

export type v1FilesUploadFileResponses = {
    /**
     * Successful Response
     */
    200: FileData;
};

export type v1FilesUploadFileResponse = v1FilesUploadFileResponses[keyof v1FilesUploadFileResponses];

export type v1FilesDeleteFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/v1/files/{file_id}';
};

export type v1FilesDeleteFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1FilesDeleteFileError = v1FilesDeleteFileErrors[keyof v1FilesDeleteFileErrors];

export type v1FilesDeleteFileResponses = {
    /**
     * Successful Response
     */
    200: DeleteFileResponse;
};

export type v1FilesDeleteFileResponse = v1FilesDeleteFileResponses[keyof v1FilesDeleteFileResponses];

export type v1FilesRetrieveFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/v1/files/{file_id}';
};

export type v1FilesRetrieveFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1FilesRetrieveFileError = v1FilesRetrieveFileErrors[keyof v1FilesRetrieveFileErrors];

export type v1FilesRetrieveFileResponses = {
    /**
     * Successful Response
     */
    200: FileData;
};

export type v1FilesRetrieveFileResponse = v1FilesRetrieveFileResponses[keyof v1FilesRetrieveFileResponses];

export type v1FilesRetrieveFileContentData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/v1/files/{file_id}/content';
};

export type v1FilesRetrieveFileContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1FilesRetrieveFileContentError = v1FilesRetrieveFileContentErrors[keyof v1FilesRetrieveFileContentErrors];

export type v1FilesRetrieveFileContentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type v1BatchesListBatchesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/v1/batches';
};

export type v1BatchesListBatchesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1BatchesListBatchesError = v1BatchesListBatchesErrors[keyof v1BatchesListBatchesErrors];

export type v1BatchesListBatchesResponses = {
    /**
     * Successful Response
     */
    200: BatchesList;
};

export type v1BatchesListBatchesResponse = v1BatchesListBatchesResponses[keyof v1BatchesListBatchesResponses];

export type v1BatchesCreateBatchData = {
    body: BatchRequest;
    path?: never;
    query?: never;
    url: '/v1/batches';
};

export type v1BatchesCreateBatchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1BatchesCreateBatchError = v1BatchesCreateBatchErrors[keyof v1BatchesCreateBatchErrors];

export type v1BatchesCreateBatchResponses = {
    /**
     * Successful Response
     */
    200: BatchData;
};

export type v1BatchesCreateBatchResponse = v1BatchesCreateBatchResponses[keyof v1BatchesCreateBatchResponses];

export type v1BatchesRetrieveBatchData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/v1/batches/{batch_id}';
};

export type v1BatchesRetrieveBatchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1BatchesRetrieveBatchError = v1BatchesRetrieveBatchErrors[keyof v1BatchesRetrieveBatchErrors];

export type v1BatchesRetrieveBatchResponses = {
    /**
     * Successful Response
     */
    200: BatchData;
};

export type v1BatchesRetrieveBatchResponse = v1BatchesRetrieveBatchResponses[keyof v1BatchesRetrieveBatchResponses];

export type v1BatchesCancelBatchData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/v1/batches/{batch_id}/cancel';
};

export type v1BatchesCancelBatchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1BatchesCancelBatchError = v1BatchesCancelBatchErrors[keyof v1BatchesCancelBatchErrors];

export type v1BatchesCancelBatchResponses = {
    /**
     * Successful Response
     */
    200: BatchData;
};

export type v1BatchesCancelBatchResponse = v1BatchesCancelBatchResponses[keyof v1BatchesCancelBatchResponses];

export type v1AudioCreateTranscriptionData = {
    body: Body_v1_audio_create_transcription;
    path?: never;
    query?: never;
    url: '/v1/audio/transcriptions';
};

export type v1AudioCreateTranscriptionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1AudioCreateTranscriptionError = v1AudioCreateTranscriptionErrors[keyof v1AudioCreateTranscriptionErrors];

export type v1AudioCreateTranscriptionResponses = {
    /**
     * Successful Response
     */
    200: TranscriptionResponse;
};

export type v1AudioCreateTranscriptionResponse = v1AudioCreateTranscriptionResponses[keyof v1AudioCreateTranscriptionResponses];

export type v1AudioCreateTranslationData = {
    body: Body_v1_audio_create_translation;
    path?: never;
    query?: never;
    url: '/v1/audio/translations';
};

export type v1AudioCreateTranslationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1AudioCreateTranslationError = v1AudioCreateTranslationErrors[keyof v1AudioCreateTranslationErrors];

export type v1AudioCreateTranslationResponses = {
    /**
     * Successful Response
     */
    200: TranslationResponse;
};

export type v1AudioCreateTranslationResponse = v1AudioCreateTranslationResponses[keyof v1AudioCreateTranslationResponses];

export type v1AudioCreateSpeechData = {
    body: SpeechRequest;
    path?: never;
    query?: never;
    url: '/v1/audio/speech';
};

export type v1AudioCreateSpeechErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type v1AudioCreateSpeechError = v1AudioCreateSpeechErrors[keyof v1AudioCreateSpeechErrors];

export type v1AudioCreateSpeechResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
