"""Manages Agent registration, discovery, and WebSocket connections."""

import asyncio
import json
import uuid as uuid_module
from datetime import UTC, datetime, timedelta

import httpx
from sqlalchemy import update
from sqlmodel import col
from websockets.client import WebSocketClientProtocol, connect

from app.core.config import settings
from app.core.logging import logger
from app.db.session import AsyncSessionMaker
from app.models import Agent, Model


class AgentManager:
    """Manages Agent lifecycle and WebSocket connections."""

    def __init__(self) -> None:
        self.agents: dict[str, Agent] = {}  # agent_id -> Agent
        self.ws_connections: dict[str, WebSocketClientProtocol] = {}
        self._reconnect_tasks: dict[str, asyncio.Task[None]] = {}
        self._event_buffers: dict[str, list[dict]] = {}
        self._connect_tasks: dict[str, asyncio.Task[None]] = {}
        self._cleanup_task: asyncio.Task[None] | None = None
        # UI subscribers per agent: agent_id -> list of asyncio.Queue
        self._event_subscribers: dict[str, list[asyncio.Queue[dict[str, object]]]] = {}

    def subscribe_events(self, agent_id: str) -> asyncio.Queue[dict[str, object]]:
        """Register a UI subscriber queue for an agent's events."""
        queue: asyncio.Queue[dict[str, object]] = asyncio.Queue(maxsize=1000)
        self._event_subscribers.setdefault(agent_id, []).append(queue)
        return queue

    def unsubscribe_events(
        self, agent_id: str, queue: asyncio.Queue[dict[str, object]]
    ) -> None:
        """Remove a UI subscriber queue for an agent's events."""
        subscribers = self._event_subscribers.get(agent_id, [])
        if queue in subscribers:
            subscribers.remove(queue)
        if not subscribers:
            self._event_subscribers.pop(agent_id, None)

    async def register_agent(self, agent_data: dict) -> Agent:
        """Register an Agent with the Frontend."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            name = agent_data["name"]

            # Agents have a UUID PK; the agent-declared agent_id is not
            # persisted. Deduplicate on the unique agent name instead.
            result = await session.execute(select(Agent).where(Agent.name == name))
            existing = result.scalar_one_or_none()

            if existing:
                # Update existing agent
                existing.status = "online"
                existing.host = agent_data["host"]
                existing.port = agent_data["port"]
                existing.gpu_info = agent_data.get("gpu_info", {})
                existing.last_seen = datetime.now(UTC)
                session.add(existing)
                agent = existing
                logger.info(f"Updated existing agent {name}")
            else:
                # Create new agent (UUID id generated by the model)
                agent = Agent(
                    name=name,
                    host=agent_data["host"],
                    port=agent_data["port"],
                    gpu_info=agent_data.get("gpu_info", {}),
                    status="online",
                    last_seen=datetime.now(UTC),
                )
                session.add(agent)
                logger.info(f"Registered new agent {name}")

            # The agent reports the server ids it currently has running. Any
            # instance still marked starting/running that is NOT in that set
            # is stale (e.g. agent restarted). Instances the agent confirms
            # as running are promoted to running — a stale "starting" row
            # (e.g. backend restarted while dispatch_start's ack was lost)
            # would otherwise block every request in wait_until_ready.
            running_ids = agent_data.get("running_server_ids") or []
            conditions = [
                col(ServerInstance.agent_id) == agent.id,
                col(ServerInstance.status).in_(["starting", "running"]),
            ]
            if running_ids:
                conditions.append(col(ServerInstance.id).not_in(running_ids))
                confirmed = await session.execute(
                    update(ServerInstance)
                    .where(
                        col(ServerInstance.agent_id) == agent.id,
                        col(ServerInstance.status) == "starting",
                        col(ServerInstance.id).in_(running_ids),
                    )
                    .values(status="running", health_status="healthy")
                )
                confirmed_count = getattr(confirmed, "rowcount", 0)
                if confirmed_count:
                    logger.info(
                        f"Marked {confirmed_count} starting server instance(s) "
                        f"as running (agent {name} reports them live)"
                    )
            stale = await session.execute(
                update(ServerInstance)
                .where(*conditions)
                .values(status="stopped", health_status="unknown")
            )
            stale_count = getattr(stale, "rowcount", 0)
            if stale_count:
                logger.info(
                    f"Marked {stale_count} server instance(s) as stopped "
                    f"for restarted agent {name}"
                )

            # The agent holds no server definitions of its own: instances
            # that should be up (auto-start aliases, previously running)
            # but are now stopped get (re)dispatched here so a restarted
            # agent restores its servers — downloads included.
            await session.commit()
            restore_result = await session.execute(
                select(ServerInstance).where(
                    col(ServerInstance.agent_id) == agent.id,
                    col(ServerInstance.status) == "stopped",
                )
            )
            to_restore = list(restore_result.scalars().all())

            await session.refresh(agent)

            self.agents[str(agent.id)] = agent
            if str(agent.id) not in self._event_buffers:
                self._event_buffers[str(agent.id)] = []

            # Start WebSocket connection (skip if one is already live)
            asyncio.create_task(self.connect_websocket(agent))

            for server in to_restore:
                try:
                    # Local import: server_startup imports agent_manager
                    from app.services.server_startup import (
                        build_start_payload,
                        dispatch_start,
                    )

                    model_id = server.model_id
                    server_id = str(server.id)
                    agent_id = str(agent.id)
                    model = await session.get(Model, model_id)
                    if model is None:
                        continue
                    server.status = "starting"
                    server.error_message = None
                    session.add(server)
                    payload = build_start_payload(server, model)
                    asyncio.create_task(dispatch_start(agent_id, server_id, payload))
                    logger.info(
                        f"Re-dispatching start for server {server_id} "
                        f"after agent {name} registered"
                    )
                except Exception as e:
                    logger.warning(
                        f"Failed to re-dispatch server {server.id} on "
                        f"agent registration: {e}"
                    )
            if to_restore:
                await session.commit()

            return agent

    async def connect_websocket(self, agent: Agent) -> None:
        """Establish and hold the WebSocket connection to an Agent.

        Exits early if a connection is already being established, so
        repeated registrations don't pile up parallel connections.
        """
        agent_id = str(agent.id)

        existing_task = self._connect_tasks.get(agent_id)
        if existing_task is not None and not existing_task.done():
            return

        task = asyncio.create_task(self._run_agent_websocket(agent))
        self._connect_tasks[agent_id] = task
        try:
            await task
        finally:
            self._connect_tasks.pop(agent_id, None)

    async def _run_agent_websocket(self, agent: Agent) -> None:
        """Run the agent event WebSocket loop until it fails."""
        ws_url = f"ws://{agent.host}:{agent.port}/ws/status"
        agent_id = str(agent.id)

        while True:
            try:
                async with connect(
                    ws_url, extra_headers={"X-Agent-ID": agent_id}
                ) as websocket:
                    self.ws_connections[agent_id] = websocket
                    agent.websocket_connected = True
                    logger.info(f"WebSocket connected to agent {agent_id}")

                    # Listen for events
                    async for message in websocket:
                        try:
                            event = json.loads(message)
                        except TypeError, ValueError:
                            logger.warning(
                                f"Unparseable message from agent {agent_id}: "
                                f"{str(message)[:120]}"
                            )
                            continue
                        await self._handle_agent_event(agent_id, event)

            except Exception as e:
                agent.websocket_connected = False
                logger.error(f"WebSocket error for agent {agent_id}: {e}")
                self._schedule_reconnect(agent)
                break

    def _schedule_reconnect(self, agent: Agent) -> None:
        """Schedule WebSocket reconnection."""
        agent_id = str(agent.id)

        if agent_id in self._reconnect_tasks:
            return

        task = asyncio.create_task(self._reconnect_loop(agent))
        self._reconnect_tasks[agent_id] = task

    async def _reconnect_loop(self, agent: Agent) -> None:
        """Attempt to reconnect to Agent."""
        agent_id = str(agent.id)
        attempts = 0

        while attempts < settings.AGENT_MAX_RECONNECT_ATTEMPTS:
            try:
                await asyncio.sleep(settings.WS_RECONNECT_INTERVAL)

                # Try to reconnect via the normal connection runner (it
                # holds the connection and parses messages).
                await self._run_agent_websocket(agent)
                return

            except Exception as e:
                attempts += 1
                logger.warning(
                    f"Reconnect attempt {attempts} failed for agent {agent_id}: {e}"
                )

        # Max attempts reached
        agent.status = "unreachable"
        self._reconnect_tasks.pop(agent_id, None)
        logger.error(f"Max reconnect attempts reached for agent {agent_id}")

    async def _handle_agent_event(self, agent_id: str, event: dict) -> None:
        """Process event from Agent."""
        # Buffer event
        if agent_id in self._event_buffers:
            buffer = self._event_buffers[agent_id]
            buffer.append(event)
            if len(buffer) > 1000:
                buffer.pop(0)

        # Fan out to UI subscribers
        for queue in self._event_subscribers.get(agent_id, []):
            try:
                queue.put_nowait(event)
            except asyncio.QueueFull:
                logger.warning(f"UI event queue full for agent {agent_id}")

        # Update database based on event type
        event_type = str(event.get("event"))
        event_data: dict = (
            event.get("data") if isinstance(event.get("data"), dict) else {}
        )

        logger.debug(f"Received event from agent {agent_id}: {event_type}")

        try:
            if event_type == "server.started":
                await self._handle_server_started(agent_id, event_data)
            elif event_type == "server.stopped":
                await self._handle_server_stopped(agent_id, event_data)
            elif event_type == "server.error":
                await self._handle_server_error(agent_id, event_data)
            elif event_type == "gpu.usage":
                await self._handle_gpu_usage(agent_id, event_data)
            elif event_type == "download.progress":
                await self._handle_download_progress(agent_id, event_data)
            elif event_type == "log.lines":
                # llama-server stdout/stderr relayed by the agent; surface it
                # in the backend log (stderr as warning for visibility).
                for entry in event_data.get("lines") or []:
                    is_stderr = entry.get("stream") == "stderr"
                    log_fn = logger.warning if is_stderr else logger.info
                    log_fn(
                        "llama-server %s [%s] agent=%s: %s",
                        str(event_data.get("server_id", ""))[:8],
                        entry.get("stream"),
                        agent_id,
                        entry.get("line", ""),
                    )
        except Exception as e:
            # A bad event must not kill the agent WebSocket (an exception
            # here previously tore down the connection and triggered a
            # reconnect storm).
            logger.warning(
                f"Failed handling {event_type} event from agent {agent_id}: {e}"
            )

    async def _handle_server_error(self, agent_id: str, data: dict) -> None:
        """Handle server.error event."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            server_id = data.get("server_id")
            if not server_id:
                return

            result = await session.execute(
                select(ServerInstance).where(ServerInstance.id == server_id)
            )
            server = result.scalar_one_or_none()

            if server:
                server.status = "error"
                server.error_message = data.get("error", "Unknown error")
                session.add(server)
                await session.commit()
                logger.warning(f"Server {server_id} error: {data.get('error')}")

    async def _handle_server_started(self, agent_id: str, data: dict) -> None:
        """Handle server.started event."""
        # Update ServerInstance in database
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            server_id = data.get("server_id")
            if server_id:
                result = await session.execute(
                    select(ServerInstance).where(ServerInstance.id == server_id)
                )
                server = result.scalar_one_or_none()

                if server:
                    server.status = "running"
                    server.health_status = "healthy"
                    server.last_health_check = datetime.now(UTC)
                    if not server.started_at:
                        server.started_at = datetime.now(UTC)
                    session.add(server)
                    await session.commit()
                    logger.info(f"Server {server_id} marked as running")

    async def _handle_server_stopped(self, agent_id: str, data: dict) -> None:
        """Handle server.stopped event."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            server_id = data.get("server_id")
            if server_id:
                result = await session.execute(
                    select(ServerInstance).where(ServerInstance.id == server_id)
                )
                server = result.scalar_one_or_none()

                if server:
                    server.status = "stopped"
                    session.add(server)
                    await session.commit()
                    logger.info(f"Server {server_id} marked as stopped")

    async def _handle_gpu_usage(self, agent_id: str, data: dict) -> None:
        """Handle gpu.usage event."""
        # Update agent GPU info
        agent = self.agents.get(agent_id)
        if agent:
            gpu_info = agent.gpu_info
            gpu_info["vram_used"] = data.get("vram_used")
            gpu_info["vram_free"] = data.get("vram_free")
            gpu_info["utilization"] = data.get("utilization")
            agent.gpu_info = gpu_info
            agent.last_seen = datetime.now(UTC)

    async def _handle_download_progress(self, agent_id: str, data: dict) -> None:
        """Handle download.progress event."""
        # Update DownloadJob in database
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import DownloadJob

            job_id = data.get("job_id")
            if not job_id:
                return
            # Auto-start downloads use synthetic ids like "server-<uuid>"
            # (not DownloadJob rows). Skip them instead of letting the UUID
            # cast fail — it used to crash the whole agent WS handler.
            try:
                job_uuid = uuid_module.UUID(str(job_id))
            except ValueError, AttributeError:
                logger.debug(f"Ignoring download.progress for non-job id {job_id}")
                return
            result = await session.execute(
                select(DownloadJob).where(DownloadJob.id == job_uuid)
            )
            job = result.scalar_one_or_none()

            if job:
                job.progress_percent = data.get("progress_percent", 0)
                job.bytes_downloaded = data.get("bytes_downloaded", 0)
                job.current_speed = data.get("speed_mbps", 0) * 1_000_000
                session.add(job)
                await session.commit()

    async def send_to_agent(
        self,
        agent_id: str,
        method: str,
        path: str,
        json: dict[str, object] | None = None,
        timeout: float = 30.0,
    ) -> dict:
        """Send HTTP request to Agent."""
        agent = self.agents.get(agent_id)
        if not agent:
            agent = await self.get_agent(agent_id)
        if not agent:
            raise ValueError(f"Agent {agent_id} not found")

        if agent.status != "online":
            raise RuntimeError(f"Agent {agent_id} is {agent.status}")

        # The agent mounts its routes at the root (e.g. /servers/list),
        # with no /api prefix.
        url = f"http://{agent.host}:{agent.port}{path}"

        async with httpx.AsyncClient(timeout=timeout) as client:
            try:
                response = await client.request(
                    method=method,
                    url=url,
                    json=json,
                )
                response.raise_for_status()
                return response.json()
            except httpx.HTTPError as e:
                logger.error(f"HTTP error to agent {agent_id}: {e}")
                raise
            except Exception as e:
                logger.error(f"Error sending to agent {agent_id}: {e}")
                raise

    async def get_agent(self, agent_id: str) -> Agent | None:
        """Get agent by ID."""
        async with AsyncSessionMaker() as session:
            import uuid as uuid_module

            try:
                agent_uuid = uuid_module.UUID(agent_id)
            except ValueError:
                return None

            return await session.get(Agent, agent_uuid)

    async def list_agents(self) -> list[dict[str, object]]:
        """List all registered agents."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            result = await session.execute(select(Agent).order_by(Agent.name))
            agents = result.scalars().all()

            return [
                {
                    "id": str(agent.id),
                    "name": agent.name,
                    "host": agent.host,
                    "port": agent.port,
                    "status": agent.status,
                    "websocket_connected": agent.websocket_connected,
                    "gpu_info": agent.gpu_info or {},
                    "last_seen": agent.last_seen,
                }
                for agent in agents
            ]

    async def cleanup_offline_agents(self) -> None:
        """Mark agents as offline if not seen recently."""
        interval = timedelta(seconds=settings.AGENT_OFFLINE_AFTER)
        async with AsyncSessionMaker() as session:
            from sqlalchemy import update

            # Find agents not seen within the offline threshold
            cutoff = datetime.now(UTC) - interval

            stmt = (
                update(Agent)
                .where(col(Agent.last_seen) < cutoff)
                .where(col(Agent.status) == "online")
                .values(status="offline")
            )

            await session.execute(stmt)
            await session.commit()

            # Update local cache
            for agent in self.agents.values():
                if not agent.last_seen:
                    continue
                last_seen = agent.last_seen
                if last_seen.tzinfo is None:
                    last_seen = last_seen.replace(tzinfo=UTC)
                if last_seen < cutoff:
                    agent.status = "offline"

    async def _cleanup_loop(self) -> None:
        """Periodically run cleanup_offline_agents until cancelled."""
        while True:
            try:
                await asyncio.sleep(settings.AGENT_CLEANUP_INTERVAL)
                await self.cleanup_offline_agents()
            except asyncio.CancelledError:
                raise
            except Exception as e:
                logger.error(f"Agent cleanup failed: {e}")

    def start_cleanup_loop(self) -> None:
        """Start the periodic agent cleanup task."""
        if not self._cleanup_task or self._cleanup_task.done():
            self._cleanup_task = asyncio.create_task(self._cleanup_loop())
            logger.info("Agent cleanup loop started")


# Global instance
agent_manager = AgentManager()
