"""Manages Agent registration, discovery, and WebSocket connections."""

import asyncio
import json
from datetime import UTC, datetime

import httpx
from sqlalchemy import update
from sqlmodel import col
from websockets.client import WebSocketClientProtocol, connect

from app.core.config import settings
from app.core.logging import logger
from app.db.session import AsyncSessionMaker
from app.models import Agent


class AgentManager:
    """Manages Agent lifecycle and WebSocket connections."""

    def __init__(self) -> None:
        self.agents: dict[str, Agent] = {}  # agent_id -> Agent
        self.ws_connections: dict[str, WebSocketClientProtocol] = {}
        self._reconnect_tasks: dict[str, asyncio.Task[None]] = {}
        self._event_buffers: dict[str, list[dict]] = {}
        self._connect_tasks: dict[str, asyncio.Task[None]] = {}
        # UI subscribers per agent: agent_id -> list of asyncio.Queue
        self._event_subscribers: dict[str, list[asyncio.Queue[dict[str, object]]]] = {}

    def subscribe_events(self, agent_id: str) -> asyncio.Queue[dict[str, object]]:
        """Register a UI subscriber queue for an agent's events."""
        queue: asyncio.Queue[dict[str, object]] = asyncio.Queue(maxsize=1000)
        self._event_subscribers.setdefault(agent_id, []).append(queue)
        return queue

    def unsubscribe_events(
        self, agent_id: str, queue: asyncio.Queue[dict[str, object]]
    ) -> None:
        """Remove a UI subscriber queue for an agent's events."""
        subscribers = self._event_subscribers.get(agent_id, [])
        if queue in subscribers:
            subscribers.remove(queue)
        if not subscribers:
            self._event_subscribers.pop(agent_id, None)

    async def register_agent(self, agent_data: dict) -> Agent:
        """Register an Agent with the Frontend."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            name = agent_data["name"]

            # Agents have a UUID PK; the agent-declared agent_id is not
            # persisted. Deduplicate on the unique agent name instead.
            result = await session.execute(select(Agent).where(Agent.name == name))
            existing = result.scalar_one_or_none()

            if existing:
                # Update existing agent
                existing.status = "online"
                existing.host = agent_data["host"]
                existing.port = agent_data["port"]
                existing.gpu_info = agent_data.get("gpu_info", {})
                existing.last_seen = datetime.utcnow()
                session.add(existing)
                agent = existing
                logger.info(f"Updated existing agent {name}")
            else:
                # Create new agent (UUID id generated by the model)
                agent = Agent(
                    name=name,
                    host=agent_data["host"],
                    port=agent_data["port"],
                    gpu_info=agent_data.get("gpu_info", {}),
                    status="online",
                    last_seen=datetime.utcnow(),
                )
                session.add(agent)
                logger.info(f"Registered new agent {name}")

            # The agent restarts with no running llama-server processes, so
            # anything still marked starting/running for it is stale.
            stale = await session.execute(
                update(ServerInstance)
                .where(
                    col(ServerInstance.agent_id) == agent.id,
                    col(ServerInstance.status).in_(["starting", "running"]),
                )
                .values(status="stopped", health_status="unknown")
            )
            stale_count = getattr(stale, "rowcount", 0)
            if stale_count:
                logger.info(
                    f"Marked {stale_count} server instance(s) as stopped "
                    f"for restarted agent {name}"
                )

            await session.commit()
            await session.refresh(agent)

            self.agents[str(agent.id)] = agent
            if str(agent.id) not in self._event_buffers:
                self._event_buffers[str(agent.id)] = []

            # Start WebSocket connection (skip if one is already live)
            asyncio.create_task(self.connect_websocket(agent))

            return agent

    async def connect_websocket(self, agent: Agent) -> None:
        """Establish and hold the WebSocket connection to an Agent.

        Exits early if a connection is already being established, so
        repeated registrations don't pile up parallel connections.
        """
        agent_id = str(agent.id)

        existing_task = self._connect_tasks.get(agent_id)
        if existing_task is not None and not existing_task.done():
            return

        task = asyncio.create_task(self._run_agent_websocket(agent))
        self._connect_tasks[agent_id] = task
        try:
            await task
        finally:
            self._connect_tasks.pop(agent_id, None)

    async def _run_agent_websocket(self, agent: Agent) -> None:
        """Run the agent event WebSocket loop until it fails."""
        ws_url = f"ws://{agent.host}:{agent.port}/ws/status"
        agent_id = str(agent.id)

        while True:
            try:
                async with connect(
                    ws_url, extra_headers={"X-Agent-ID": agent_id}
                ) as websocket:
                    self.ws_connections[agent_id] = websocket
                    agent.websocket_connected = True
                    logger.info(f"WebSocket connected to agent {agent_id}")

                    # Listen for events
                    async for message in websocket:
                        try:
                            event = json.loads(message)
                        except TypeError, ValueError:
                            logger.warning(
                                f"Unparseable message from agent {agent_id}: "
                                f"{str(message)[:120]}"
                            )
                            continue
                        await self._handle_agent_event(agent_id, event)

            except Exception as e:
                agent.websocket_connected = False
                logger.error(f"WebSocket error for agent {agent_id}: {e}")
                self._schedule_reconnect(agent)
                break

    def _schedule_reconnect(self, agent: Agent) -> None:
        """Schedule WebSocket reconnection."""
        agent_id = str(agent.id)

        if agent_id in self._reconnect_tasks:
            return

        task = asyncio.create_task(self._reconnect_loop(agent))
        self._reconnect_tasks[agent_id] = task

    async def _reconnect_loop(self, agent: Agent) -> None:
        """Attempt to reconnect to Agent."""
        agent_id = str(agent.id)
        attempts = 0

        while attempts < settings.AGENT_MAX_RECONNECT_ATTEMPTS:
            try:
                await asyncio.sleep(settings.WS_RECONNECT_INTERVAL)

                # Try to reconnect via the normal connection runner (it
                # holds the connection and parses messages).
                await self._run_agent_websocket(agent)
                return

            except Exception as e:
                attempts += 1
                logger.warning(
                    f"Reconnect attempt {attempts} failed for agent {agent_id}: {e}"
                )

        # Max attempts reached
        agent.status = "unreachable"
        self._reconnect_tasks.pop(agent_id, None)
        logger.error(f"Max reconnect attempts reached for agent {agent_id}")

    async def _handle_agent_event(self, agent_id: str, event: dict) -> None:
        """Process event from Agent."""
        # Buffer event
        if agent_id in self._event_buffers:
            buffer = self._event_buffers[agent_id]
            buffer.append(event)
            if len(buffer) > 1000:
                buffer.pop(0)

        # Fan out to UI subscribers
        for queue in self._event_subscribers.get(agent_id, []):
            try:
                queue.put_nowait(event)
            except asyncio.QueueFull:
                logger.warning(f"UI event queue full for agent {agent_id}")

        # Update database based on event type
        event_type = str(event.get("event"))
        event_data: dict = (
            event.get("data") if isinstance(event.get("data"), dict) else {}
        )

        logger.debug(f"Received event from agent {agent_id}: {event_type}")

        if event_type == "server.started":
            await self._handle_server_started(agent_id, event_data)
        elif event_type == "server.stopped":
            await self._handle_server_stopped(agent_id, event_data)
        elif event_type == "server.error":
            await self._handle_server_error(agent_id, event_data)
        elif event_type == "gpu.usage":
            await self._handle_gpu_usage(agent_id, event_data)
        elif event_type == "download.progress":
            await self._handle_download_progress(agent_id, event_data)

    async def _handle_server_error(self, agent_id: str, data: dict) -> None:
        """Handle server.error event."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            server_id = data.get("server_id")
            if not server_id:
                return

            result = await session.execute(
                select(ServerInstance).where(ServerInstance.id == server_id)
            )
            server = result.scalar_one_or_none()

            if server:
                server.status = "error"
                server.error_message = data.get("error", "Unknown error")
                session.add(server)
                await session.commit()
                logger.warning(f"Server {server_id} error: {data.get('error')}")

    async def _handle_server_started(self, agent_id: str, data: dict) -> None:
        """Handle server.started event."""
        # Update ServerInstance in database
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            server_id = data.get("server_id")
            if server_id:
                result = await session.execute(
                    select(ServerInstance).where(ServerInstance.id == server_id)
                )
                server = result.scalar_one_or_none()

                if server:
                    server.status = "running"
                    server.health_status = "healthy"
                    server.last_health_check = datetime.now(UTC)
                    if not server.started_at:
                        server.started_at = datetime.now(UTC)
                    session.add(server)
                    await session.commit()
                    logger.info(f"Server {server_id} marked as running")

    async def _handle_server_stopped(self, agent_id: str, data: dict) -> None:
        """Handle server.stopped event."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import ServerInstance

            server_id = data.get("server_id")
            if server_id:
                result = await session.execute(
                    select(ServerInstance).where(ServerInstance.id == server_id)
                )
                server = result.scalar_one_or_none()

                if server:
                    server.status = "stopped"
                    session.add(server)
                    await session.commit()
                    logger.info(f"Server {server_id} marked as stopped")

    async def _handle_gpu_usage(self, agent_id: str, data: dict) -> None:
        """Handle gpu.usage event."""
        # Update agent GPU info
        agent = self.agents.get(agent_id)
        if agent:
            gpu_info = agent.gpu_info
            gpu_info["vram_used"] = data.get("vram_used")
            gpu_info["vram_free"] = data.get("vram_free")
            gpu_info["utilization"] = data.get("utilization")
            agent.gpu_info = gpu_info
            agent.last_seen = datetime.now(UTC)

    async def _handle_download_progress(self, agent_id: str, data: dict) -> None:
        """Handle download.progress event."""
        # Update DownloadJob in database
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            from app.models import DownloadJob

            job_id = data.get("job_id")
            if job_id:
                result = await session.execute(
                    select(DownloadJob).where(DownloadJob.id == job_id)
                )
                job = result.scalar_one_or_none()

                if job:
                    job.progress_percent = data.get("progress_percent", 0)
                    job.bytes_downloaded = data.get("bytes_downloaded", 0)
                    job.current_speed = data.get("speed_mbps", 0) * 1_000_000
                    session.add(job)
                    await session.commit()

    async def send_to_agent(
        self,
        agent_id: str,
        method: str,
        path: str,
        json: dict[str, object] | None = None,
        timeout: float = 30.0,
    ) -> dict:
        """Send HTTP request to Agent."""
        agent = self.agents.get(agent_id)
        if not agent:
            agent = await self.get_agent(agent_id)
        if not agent:
            raise ValueError(f"Agent {agent_id} not found")

        if agent.status != "online":
            raise RuntimeError(f"Agent {agent_id} is {agent.status}")

        # The agent mounts its routes at the root (e.g. /servers/list),
        # with no /api prefix.
        url = f"http://{agent.host}:{agent.port}{path}"

        async with httpx.AsyncClient(timeout=timeout) as client:
            try:
                response = await client.request(
                    method=method,
                    url=url,
                    json=json,
                )
                response.raise_for_status()
                return response.json()
            except httpx.HTTPError as e:
                logger.error(f"HTTP error to agent {agent_id}: {e}")
                raise
            except Exception as e:
                logger.error(f"Error sending to agent {agent_id}: {e}")
                raise

    async def get_agent(self, agent_id: str) -> Agent | None:
        """Get agent by ID."""
        async with AsyncSessionMaker() as session:
            import uuid as uuid_module

            try:
                agent_uuid = uuid_module.UUID(agent_id)
            except ValueError:
                return None

            return await session.get(Agent, agent_uuid)

    async def list_agents(self) -> list[dict[str, object]]:
        """List all registered agents."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import select

            result = await session.execute(select(Agent).order_by(Agent.name))
            agents = result.scalars().all()

            return [
                {
                    "id": str(agent.id),
                    "name": agent.name,
                    "host": agent.host,
                    "port": agent.port,
                    "status": agent.status,
                    "websocket_connected": agent.websocket_connected,
                    "gpu_info": agent.gpu_info or {},
                    "last_seen": agent.last_seen,
                }
                for agent in agents
            ]

    async def cleanup_offline_agents(self) -> None:
        """Mark agents as offline if not seen recently."""
        async with AsyncSessionMaker() as session:
            from sqlalchemy import update

            # Find agents not seen in last 5 minutes
            cutoff = datetime.utcnow()

            stmt = (
                update(Agent)
                .where(Agent.last_seen < cutoff)
                .where(Agent.status == "online")
                .values(status="offline")
            )

            await session.execute(stmt)
            await session.commit()

            # Update local cache
            for agent in self.agents.values():
                if agent.last_seen and agent.last_seen < cutoff:
                    agent.status = "offline"


# Global instance
agent_manager = AgentManager()
