"""initial squashed schema

Revision ID: 0140d6ad9f48
Revises: 
Create Date: 2026-10-03 22:40:16.329148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0140d6ad9f48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('dns', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('total_vram_bytes', sa.BigInteger(), nullable=False),
    sa.Column('hardware', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('provider_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('backend_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('vram_required_bytes', sa.BigInteger(), nullable=False),
    sa.Column('idle_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registration_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('registration_token')
    )
    op.create_index('idx_provider_definitions_type', 'provider_definitions', ['provider_type'], unique=False)
    op.create_table('provider_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('provider_definition_id', sa.Uuid(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('instance_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('backend_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('websocket_connected', sa.Boolean(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('assigned_gpus', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_definition_id'], ['provider_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_instances_backend_status', 'provider_instances', ['backend_status'], unique=False)
    op.create_index('idx_provider_instances_def', 'provider_instances', ['provider_definition_id'], unique=False)
    op.create_index('idx_provider_instances_instance_status', 'provider_instances', ['instance_status'], unique=False)
    op.create_index('idx_provider_instances_machine_def', 'provider_instances', ['machine_id', 'provider_definition_id'], unique=True)
    op.create_table('responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('response_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('previous_response_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('input_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_definition_id', sa.Uuid(), nullable=False),
    sa.Column('provider_instance_id', sa.Uuid(), nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('incomplete_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('store', sa.Boolean(), nullable=False),
    sa.Column('background', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_definition_id'], ['provider_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_instance_id'], ['provider_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_index('idx_responses_created_at', 'responses', ['created_at'], unique=False)
    op.create_index('idx_responses_previous_response_id', 'responses', ['previous_response_id'], unique=False)
    op.create_index('idx_responses_provider_definition_id', 'responses', ['provider_definition_id'], unique=False)
    op.create_table('token_usage_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_instance_id', sa.Uuid(), nullable=True),
    sa.Column('provider_definition_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_ms', sa.Float(), nullable=False),
    sa.Column('predicted_ms', sa.Float(), nullable=False),
    sa.Column('prompt_per_second', sa.Float(), nullable=False),
    sa.Column('predicted_per_second', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_definition_id'], ['provider_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_instance_id'], ['provider_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_samples_created_at', 'token_usage_samples', ['created_at'], unique=False)
    op.create_index('idx_token_usage_samples_instance_created', 'token_usage_samples', ['provider_instance_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_usage_samples_instance_created', table_name='token_usage_samples')
    op.drop_index('idx_token_usage_samples_created_at', table_name='token_usage_samples')
    op.drop_table('token_usage_samples')
    op.drop_index('idx_responses_provider_definition_id', table_name='responses')
    op.drop_index('idx_responses_previous_response_id', table_name='responses')
    op.drop_index('idx_responses_created_at', table_name='responses')
    op.drop_table('responses')
    op.drop_index('idx_provider_instances_machine_def', table_name='provider_instances')
    op.drop_index('idx_provider_instances_instance_status', table_name='provider_instances')
    op.drop_index('idx_provider_instances_def', table_name='provider_instances')
    op.drop_index('idx_provider_instances_backend_status', table_name='provider_instances')
    op.drop_table('provider_instances')
    op.drop_index('idx_provider_definitions_type', table_name='provider_definitions')
    op.drop_table('provider_definitions')
    op.drop_table('machines')
    # ### end Alembic commands ###
