"""Add Inference Matrix models

Revision ID: 10b7b0fc6f3a
Revises: 
Create Date: 2026-09-17 20:58:17.557832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '10b7b0fc6f3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('rate_limit_requests', sa.Integer(), nullable=True),
    sa.Column('rate_limit_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checksum_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_metadata', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_created_at', 'files', ['created_at'], unique=False)
    op.create_index('idx_files_purpose', 'files', ['purpose'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('architecture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_count', sa.Integer(), nullable=True),
    sa.Column('quantization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supports_embeddings', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_models_architecture', 'models', ['architecture'], unique=False)
    op.create_index('idx_models_name', 'models', ['name'], unique=False)
    op.create_index('idx_models_source', 'models', ['source'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=True)
    op.create_table('audio_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_file_id', sa.Uuid(), nullable=False),
    sa.Column('output_file_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['input_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_jobs_input_file', 'audio_jobs', ['input_file_id'], unique=False)
    op.create_index('idx_audio_jobs_status', 'audio_jobs', ['status'], unique=False)
    op.create_index('idx_audio_jobs_type', 'audio_jobs', ['job_type'], unique=False)
    op.create_table('batch_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('input_file_id', sa.Uuid(), nullable=False),
    sa.Column('output_file_id', sa.Uuid(), nullable=True),
    sa.Column('results_file_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completion_window_hours', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('processed_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['input_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['results_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_jobs_expires_at', 'batch_jobs', ['expires_at'], unique=False)
    op.create_index('idx_batch_jobs_status', 'batch_jobs', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('response_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_items', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('output_items', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('conversation_metadata', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index('idx_conversations_model_id', 'conversations', ['model_id'], unique=False)
    op.create_index('idx_conversations_parent_id', 'conversations', ['parent_id'], unique=False)
    op.create_index('idx_conversations_response_id', 'conversations', ['response_id'], unique=False)
    op.create_table('download_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=True),
    sa.Column('current_speed', sa.Integer(), nullable=False),
    sa.Column('average_speed', sa.Integer(), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('pause_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('destination_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_download_jobs_created_at', 'download_jobs', ['created_at'], unique=False)
    op.create_index('idx_download_jobs_model_id', 'download_jobs', ['model_id'], unique=False)
    op.create_index('idx_download_jobs_status', 'download_jobs', ['status'], unique=False)
    op.create_table('server_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('process_command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens_generated', sa.Integer(), nullable=False),
    sa.Column('average_response_time_ms', sa.Float(), nullable=False),
    sa.Column('vram_usage_bytes', sa.Integer(), nullable=True),
    sa.Column('ram_usage_bytes', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('inactivity_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('auto_shutdown_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port')
    )
    op.create_index('idx_server_instances_model_id', 'server_instances', ['model_id'], unique=False)
    op.create_index('idx_server_instances_port', 'server_instances', ['port'], unique=False)
    op.create_index('idx_server_instances_status', 'server_instances', ['status'], unique=False)
    op.create_table('prompt_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('cache_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('llama_cache_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('cache_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_cache_cache_key', 'prompt_cache', ['cache_key'], unique=False)
    op.create_index('idx_prompt_cache_conversation_id', 'prompt_cache', ['conversation_id'], unique=False)
    op.create_index('idx_prompt_cache_expires_at', 'prompt_cache', ['expires_at'], unique=False)
    op.create_index('idx_prompt_cache_model_id', 'prompt_cache', ['model_id'], unique=False)
    op.create_index(op.f('ix_prompt_cache_cache_key'), 'prompt_cache', ['cache_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_cache_cache_key'), table_name='prompt_cache')
    op.drop_index('idx_prompt_cache_model_id', table_name='prompt_cache')
    op.drop_index('idx_prompt_cache_expires_at', table_name='prompt_cache')
    op.drop_index('idx_prompt_cache_conversation_id', table_name='prompt_cache')
    op.drop_index('idx_prompt_cache_cache_key', table_name='prompt_cache')
    op.drop_table('prompt_cache')
    op.drop_index('idx_server_instances_status', table_name='server_instances')
    op.drop_index('idx_server_instances_port', table_name='server_instances')
    op.drop_index('idx_server_instances_model_id', table_name='server_instances')
    op.drop_table('server_instances')
    op.drop_index('idx_download_jobs_status', table_name='download_jobs')
    op.drop_index('idx_download_jobs_model_id', table_name='download_jobs')
    op.drop_index('idx_download_jobs_created_at', table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index('idx_conversations_response_id', table_name='conversations')
    op.drop_index('idx_conversations_parent_id', table_name='conversations')
    op.drop_index('idx_conversations_model_id', table_name='conversations')
    op.drop_index('idx_conversations_created_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_batch_jobs_status', table_name='batch_jobs')
    op.drop_index('idx_batch_jobs_expires_at', table_name='batch_jobs')
    op.drop_table('batch_jobs')
    op.drop_index('idx_audio_jobs_type', table_name='audio_jobs')
    op.drop_index('idx_audio_jobs_status', table_name='audio_jobs')
    op.drop_index('idx_audio_jobs_input_file', table_name='audio_jobs')
    op.drop_table('audio_jobs')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index('idx_models_source', table_name='models')
    op.drop_index('idx_models_name', table_name='models')
    op.drop_index('idx_models_architecture', table_name='models')
    op.drop_table('models')
    op.drop_index('idx_files_purpose', table_name='files')
    op.drop_index('idx_files_created_at', table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_is_active', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
