"""Add mtp_draft_max column to ServerInstance

Revision ID: 3cc6291025fe
Revises: f3a9c2d41b07
Create Date: 2026-09-24 15:17:54.447406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc6291025fe'
down_revision: Union[str, Sequence[str], None] = 'f3a9c2d41b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'context_length')
    op.create_index(op.f('ix_responses_response_id'), 'responses', ['response_id'], unique=False)
    op.add_column('server_instances', sa.Column('mtp_draft_max', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_server_instances_alias'), table_name='server_instances')
    op.drop_index(op.f('idx_server_instances_mmproj_model_id'), table_name='server_instances')
    op.drop_constraint(op.f('uq_server_instances_alias'), 'server_instances', type_='unique')
    op.create_index(op.f('ix_server_instances_alias'), 'server_instances', ['alias'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_instances_alias'), table_name='server_instances')
    op.create_unique_constraint(op.f('uq_server_instances_alias'), 'server_instances', ['alias'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_server_instances_mmproj_model_id'), 'server_instances', ['mmproj_model_id'], unique=False)
    op.create_index(op.f('idx_server_instances_alias'), 'server_instances', ['alias'], unique=False)
    op.drop_column('server_instances', 'mtp_draft_max')
    op.drop_index(op.f('ix_responses_response_id'), table_name='responses')
    op.add_column('models', sa.Column('context_length', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
