"""Add agent_id to prompt_cache

Revision ID: ee52a27d7836
Revises: a9d4d25cef08
Create Date: 2026-09-19 20:29:01.331514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee52a27d7836'
down_revision: Union[str, Sequence[str], None] = 'a9d4d25cef08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_cache', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'prompt_cache', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_cache', type_='foreignkey')
    op.drop_column('prompt_cache', 'agent_id')
    # ### end Alembic commands ###
