/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutModelsRouteImport } from './routes/_layout/models'
import { Route as LayoutServerInstancesRouteImport } from './routes/_layout/server-instances'
import { Route as LayoutAudioIndexRouteImport } from './routes/_layout/audio/index'
import { Route as LayoutChatIndexRouteImport } from './routes/_layout/chat/index'
import { Route as LayoutCompletionsIndexRouteImport } from './routes/_layout/completions/index'
import { Route as LayoutEmbeddingsIndexRouteImport } from './routes/_layout/embeddings/index'
import { Route as LayoutResponsesIndexRouteImport } from './routes/_layout/responses/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsRoute = LayoutModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServerInstancesRoute = LayoutServerInstancesRouteImport.update({
  id: '/server-instances',
  path: '/server-instances',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAudioIndexRoute = LayoutAudioIndexRouteImport.update({
  id: '/audio/',
  path: '/audio/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatIndexRoute = LayoutChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompletionsIndexRoute = LayoutCompletionsIndexRouteImport.update({
  id: '/completions/',
  path: '/completions/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmbeddingsIndexRoute = LayoutEmbeddingsIndexRouteImport.update({
  id: '/embeddings/',
  path: '/embeddings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResponsesIndexRoute = LayoutResponsesIndexRouteImport.update({
  id: '/responses/',
  path: '/responses/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/agents': typeof LayoutAgentsRoute
  '/models': typeof LayoutModelsRoute
  '/server-instances': typeof LayoutServerInstancesRoute
  '/audio/': typeof LayoutAudioIndexRoute
  '/chat/': typeof LayoutChatIndexRoute
  '/completions/': typeof LayoutCompletionsIndexRoute
  '/embeddings/': typeof LayoutEmbeddingsIndexRoute
  '/responses/': typeof LayoutResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/agents': typeof LayoutAgentsRoute
  '/models': typeof LayoutModelsRoute
  '/server-instances': typeof LayoutServerInstancesRoute
  '/': typeof LayoutIndexRoute
  '/audio': typeof LayoutAudioIndexRoute
  '/chat': typeof LayoutChatIndexRoute
  '/completions': typeof LayoutCompletionsIndexRoute
  '/embeddings': typeof LayoutEmbeddingsIndexRoute
  '/responses': typeof LayoutResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/models': typeof LayoutModelsRoute
  '/_layout/server-instances': typeof LayoutServerInstancesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/audio/': typeof LayoutAudioIndexRoute
  '/_layout/chat/': typeof LayoutChatIndexRoute
  '/_layout/completions/': typeof LayoutCompletionsIndexRoute
  '/_layout/embeddings/': typeof LayoutEmbeddingsIndexRoute
  '/_layout/responses/': typeof LayoutResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/models'
    | '/server-instances'
    | '/audio/'
    | '/chat/'
    | '/completions/'
    | '/embeddings/'
    | '/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/models'
    | '/server-instances'
    | '/'
    | '/audio'
    | '/chat'
    | '/completions'
    | '/embeddings'
    | '/responses'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/agents'
    | '/_layout/models'
    | '/_layout/server-instances'
    | '/_layout/'
    | '/_layout/audio/'
    | '/_layout/chat/'
    | '/_layout/completions/'
    | '/_layout/embeddings/'
    | '/_layout/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models': {
      id: '/_layout/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof LayoutModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/server-instances': {
      id: '/_layout/server-instances'
      path: '/server-instances'
      fullPath: '/server-instances'
      preLoaderRoute: typeof LayoutServerInstancesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audio/': {
      id: '/_layout/audio/'
      path: '/audio'
      fullPath: '/audio/'
      preLoaderRoute: typeof LayoutAudioIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/': {
      id: '/_layout/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof LayoutChatIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/completions/': {
      id: '/_layout/completions/'
      path: '/completions'
      fullPath: '/completions/'
      preLoaderRoute: typeof LayoutCompletionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/embeddings/': {
      id: '/_layout/embeddings/'
      path: '/embeddings'
      fullPath: '/embeddings/'
      preLoaderRoute: typeof LayoutEmbeddingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/responses/': {
      id: '/_layout/responses/'
      path: '/responses'
      fullPath: '/responses/'
      preLoaderRoute: typeof LayoutResponsesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutModelsRoute: typeof LayoutModelsRoute
  LayoutServerInstancesRoute: typeof LayoutServerInstancesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAudioIndexRoute: typeof LayoutAudioIndexRoute
  LayoutChatIndexRoute: typeof LayoutChatIndexRoute
  LayoutCompletionsIndexRoute: typeof LayoutCompletionsIndexRoute
  LayoutEmbeddingsIndexRoute: typeof LayoutEmbeddingsIndexRoute
  LayoutResponsesIndexRoute: typeof LayoutResponsesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutModelsRoute: LayoutModelsRoute,
  LayoutServerInstancesRoute: LayoutServerInstancesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAudioIndexRoute: LayoutAudioIndexRoute,
  LayoutChatIndexRoute: LayoutChatIndexRoute,
  LayoutCompletionsIndexRoute: LayoutCompletionsIndexRoute,
  LayoutEmbeddingsIndexRoute: LayoutEmbeddingsIndexRoute,
  LayoutResponsesIndexRoute: LayoutResponsesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
