/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutDefinitionsRouteImport } from './routes/_layout/definitions'
import { Route as LayoutInstancesRouteImport } from './routes/_layout/instances'
import { Route as LayoutMachinesRouteImport } from './routes/_layout/machines'
import { Route as LayoutPlaygroundRouteImport } from './routes/_layout/playground'
import { Route as LayoutProviderTypesRouteImport } from './routes/_layout/provider-types'
import { Route as LayoutResponsesRouteImport } from './routes/_layout/responses'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDefinitionsRoute = LayoutDefinitionsRouteImport.update({
  id: '/definitions',
  path: '/definitions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInstancesRoute = LayoutInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMachinesRoute = LayoutMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaygroundRoute = LayoutPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProviderTypesRoute = LayoutProviderTypesRouteImport.update({
  id: '/provider-types',
  path: '/provider-types',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResponsesRoute = LayoutResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/agents': typeof LayoutAgentsRoute
  '/definitions': typeof LayoutDefinitionsRoute
  '/instances': typeof LayoutInstancesRoute
  '/machines': typeof LayoutMachinesRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/provider-types': typeof LayoutProviderTypesRoute
  '/responses': typeof LayoutResponsesRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/agents': typeof LayoutAgentsRoute
  '/definitions': typeof LayoutDefinitionsRoute
  '/instances': typeof LayoutInstancesRoute
  '/machines': typeof LayoutMachinesRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/provider-types': typeof LayoutProviderTypesRoute
  '/responses': typeof LayoutResponsesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/definitions': typeof LayoutDefinitionsRoute
  '/_layout/instances': typeof LayoutInstancesRoute
  '/_layout/machines': typeof LayoutMachinesRoute
  '/_layout/playground': typeof LayoutPlaygroundRoute
  '/_layout/provider-types': typeof LayoutProviderTypesRoute
  '/_layout/responses': typeof LayoutResponsesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/definitions'
    | '/instances'
    | '/machines'
    | '/playground'
    | '/provider-types'
    | '/responses'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/definitions'
    | '/instances'
    | '/machines'
    | '/playground'
    | '/provider-types'
    | '/responses'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/agents'
    | '/_layout/definitions'
    | '/_layout/instances'
    | '/_layout/machines'
    | '/_layout/playground'
    | '/_layout/provider-types'
    | '/_layout/responses'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/definitions': {
      id: '/_layout/definitions'
      path: '/definitions'
      fullPath: '/definitions'
      preLoaderRoute: typeof LayoutDefinitionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/instances': {
      id: '/_layout/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof LayoutInstancesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/machines': {
      id: '/_layout/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof LayoutMachinesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playground': {
      id: '/_layout/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof LayoutPlaygroundRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/provider-types': {
      id: '/_layout/provider-types'
      path: '/provider-types'
      fullPath: '/provider-types'
      preLoaderRoute: typeof LayoutProviderTypesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/responses': {
      id: '/_layout/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof LayoutResponsesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutDefinitionsRoute: typeof LayoutDefinitionsRoute
  LayoutInstancesRoute: typeof LayoutInstancesRoute
  LayoutMachinesRoute: typeof LayoutMachinesRoute
  LayoutPlaygroundRoute: typeof LayoutPlaygroundRoute
  LayoutProviderTypesRoute: typeof LayoutProviderTypesRoute
  LayoutResponsesRoute: typeof LayoutResponsesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutDefinitionsRoute: LayoutDefinitionsRoute,
  LayoutInstancesRoute: LayoutInstancesRoute,
  LayoutMachinesRoute: LayoutMachinesRoute,
  LayoutPlaygroundRoute: LayoutPlaygroundRoute,
  LayoutProviderTypesRoute: LayoutProviderTypesRoute,
  LayoutResponsesRoute: LayoutResponsesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
