"""Add agent tracking and update server instances

Revision ID: c0c91c9ed06d
Revises: a180d3621a68
Create Date: 2026-09-18 01:28:02.370306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0c91c9ed06d'
down_revision: Union[str, Sequence[str], None] = 'a180d3621a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('websocket_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_name', 'agents', ['name'], unique=True)
    op.create_index('idx_agents_status', 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('server_instances', sa.Column('agent_id', sa.Uuid(), nullable=False))
    op.add_column('server_instances', sa.Column('proxy_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'server_instances', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'server_instances', type_='foreignkey')
    op.drop_column('server_instances', 'proxy_url')
    op.drop_column('server_instances', 'agent_id')
    op.drop_column('item', 'created_at')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index('idx_agents_status', table_name='agents')
    op.drop_index('idx_agents_name', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
